### ISSUE TITLE
EnchantmentCracker Fails After First Enchantment Table Input

### ISSUE THREAD

**Issue by TheGuy920** [Earthcomputer/EnchantmentCracker#102]
I am in 1.14.4 and I can not get the cracker to work after the first input, it usually narrows it down to 100 million possibilities. I start at 15 then make my way down to 14, after I input 14 and the xp values, it says there are 0 possible seeds, every time, doesnt seem to mater what I do, I've tried it in vanilla, single player, minecraft 1.14.4

I am also using 1.4.3 enchcracker

**Comment by Earthcomputer** [comment]
Try using the mod instead https://github.com/Earthcomputer/clientcommands/releases which gives you more detailed information about what went wrong.
You have to first enable it by running the command `/ctemprule set enchantingPrediction true`, then there is a built-in enchantment cracker which works the same way as this one.
Let me know how it goes.

**Comment by TheGuy920** [comment]
I will do

**Comment by leumasme** [comment]
When your state is cracked, use
/ctemprule set enchantingPrediction true
to enable Previews for the current enchant in the enchanting table, and
/cenchant <itemname> [...]
For [...] you can then append any number of 
<with | without> <enchamtnemtname> <enchantlevel>
You can also use * as enchantlevel to accept/reject any level
So an example command would be
/cenchant minecraft:diamond_sword with minecraft:unbreaking 3 with minecraft:sharpness 4 without minecraft:knockback *
This would guide you to enchant a sword wich is guaranteed to have Unbreaking3, Sharpness4, and guaranteed to NOT have ANY level of Knockback.
The cenchant command will then automatically drop the required number of items, tell you to do a dummy enchantment and then tell you how many bookshelfs to use and wich enchantment slot.

**Comment by Earthcomputer** [comment]
Is this still an issue in the latest version of the cracker, 1.4.4?

**Comment by TheGuy920** [comment]
Sorry it took so long to respond, I can safely say the modded version works 100% and I am so grateful for it, i just got distracted using it so much, thx
