### ISSUE TITLE
Is there way to make cmd not close?

### ISSUE THREAD

**Issue by Luky0805** [Earthcomputer/EnchantmentCracker#103]
I always used the .jar files instead of the .bat files, when it comes to your enchanter cracker, but in version >= 1.4 jar doesn't do anything, and when I try to open bat file as I am originally supposed to do, it immediately closes, waiting and still nothing.
The cmd might say something useful, for me and the creator, but unfortunately I can't see it.

**Comment by the-strange-quark** [comment]
check if your java jre is upto date. find the link here : https://www.java.com/en/download/windows-64bit.jsp.
did the trick for me.

**Comment by Luky0805** [comment]
Did nothing. & what's your java version (I am not sure if on oracle's site you can download older versions, but I would like to know that, it may and may not start because of version.)?
And, is there any way to make cmd not close? Because it's more likely that it's not caused by version of java, but more likely by something else which I can't even know what it is.
Windows 10, 64 bit version.

**Comment by Earthcomputer** [comment]
Try version 1.4.4

**Comment by Luky0805** [comment]
Unfortunately, your new version didn't fix anything.
But,managed to fix that. It might help others, or they have other issue.
I 
-----
windows settings
search for "edit the system environment variables"
advanced
environment variables
User variables for (Name of the user.)
create variable PATH
enter path to java's bin folder, in my case "C:\Program Files\Java\jre1.8.0_221\bin;"
-----
It might not add variable because of new versions, but I don't know until someone looks at the code.
-----
**Yea and, please** add a option where we can select items which we want to enchant (Enter names, some of items are missing like shears, etc.)
