### ISSUE TITLE
Many enchantments broken on books

### ISSUE THREAD

**Issue by Rolandsteele** [Earthcomputer/EnchantmentCracker#105]
Essentially, any time I attempt to run sweeping edge on a book, it seems to pay out the wrong enchant (lure, eff, etc), might be the same for swords too. I tried this as a part of multiple enchantments in one sitting, and I figured that I'm able to press "done" on that particular incorrect process, and still move onto one that is different, and end up with the right enchants. For example, I enchanted my diamond sword with sharp IV, fire aspect II, and unbreaking III. Perfect success. Next I continued from that, and started the process on putting Sweeping Edge III onto a book (later for use on the same sword, note it was also noted impossible to put this enchant combined with sharp 4, or unbreaking, unsure if intentional). That ended up spitting out lure II. I pressed done, and figured I'd try for a sharp IV book just to see if I was still operating on a consistent seed, and sure enough, I got what I asked for. Same issue happens with all variants of Sweeping Edge that I know of, and all spit out varied results.

**Comment by Rolandsteele** [comment]
I'm going to see if I can run more tests with that specific enchantment. I'm using the latest version of the cracker, and am on the correct game version in the drop-down

**Comment by Earthcomputer** [comment]
1. Are you sure it's 1.14.3 exclusive and doesn't happen on 1.14.4?
2. For books, make extra sure you're using the exact right number of bookshelves if it tells you to use less than 15, as having too many can give the wrong enchants.

**Comment by Rolandsteele** [comment]
Yeah, I tried it on a server that only allows me to connect with a 1.14.3 client, I'm running a singleplayer test now, but it was consistent there.

**Comment by Rolandsteele** [comment]
Just tried it in singleplayer, attempted to enchant a sweeping edge 3 book, got power 3 instead

**Comment by Rolandsteele** [comment]
And I'm unsure if it also happens in 1.14.4, never really occurred to me, so after a couple more educational tests here, I'll switch versions, and see what happens.

**Comment by Earthcomputer** [comment]
Knowing whether it happens in 1.14.4 is pretty crucial haha. It makes the difference whether I have to treat .3 and .4 as different versions in the dropdown or not.

**Comment by Rolandsteele** [comment]
I'll test it, no worries. Just to narrow it down, there's a bit of a pattern. Disregard the power 3 result, that was faulty. I did four or five more tests on 1.14.3, and it's consistently giving me a permutation of lure.

**Comment by Rolandsteele** [comment]
Just tested it on both versions, still giving me lure, or something. Going to try it on various swords now.

**Comment by Rolandsteele** [comment]
Seems like on diamond swords, it treats sweeping as unbreaking.

**Comment by Earthcomputer** [comment]
I can confirm that I also failed to get sweeping edge on a book in my own testing in 1.14.4

**Comment by Earthcomputer** [comment]
I think it was broken in [this commit](https://github.com/Earthcomputer/EnchantmentCracker/commit/c646b2474aa53f1766981a6b8a09e598d0b5325d) where I stupidly reordered the enchantments to match what version they were added in rather than the order the enchantment list is internally, which breaks many enchantments on books, not sure about any other items.

**Comment by Rolandsteele** [comment]
Yeah, sweeping edge also is impossible on all swords, it's guaranteed  unb 3 though, if you request sweeping 3. ALSO I figured why not try lure itself on a book, and I discovered that it is also fairly broken, I request lure 3, and I get... inconsistent results at best. I got lure 2 a handful of times, and random other enchants others. Also to note, an odd pattern where on the times where lure didn't pay out at all, the dummy item enchant tier 3 would always be sweeping III. Might've been luck, but figured I'd note it.

**Comment by Earthcomputer** [comment]
Basically, as you've noticed, some enchants have been substituted with others, but due to a special case in the enchanting code for enchanting books, that substitute sometimes may not appear for books.

**Comment by Rolandsteele** [comment]
Yeah, I figured. Hopefully it's not a difficult patch

**Comment by MCRcortex** [comment]
you could always use clientcommands :P

**Comment by Earthcomputer** [comment]
He said he was on a 1.14.3 server.

**Comment by MCRcortex** [comment]
compile for 1.14.3?

**Comment by Rolandsteele** [comment]
I hate to be that guy on this uh, forum, but I'm the "explain it to me like I'm 5" kind of crowd. I'd *love* to get the clientcommands going but God I am ignorant.

**Comment by Earthcomputer** [comment]
I updated the [readme](https://github.com/Earthcomputer/clientcommands/blob/fabric/README.md) with clearer instructions a few days ago, feel free to create an issue on that repo if you need further clarification.

**Comment by Earthcomputer** [comment]
[Fixed](https://github.com/Earthcomputer/EnchantmentCracker/commit/754734b4baa2f5cff2c13cf96917bc92d495c5d2)

**Comment by Earthcomputer** [comment]
Try the new release

**Comment by Rolandsteele** [comment]
Are clientcommands good to go too, or is that awaiting a patch as well?

**Comment by Earthcomputer** [comment]
clientcommands is not affected, as it uses the game's own enchanting code to simulate enchantments.

**Comment by Rolandsteele** [comment]
Much appreciated.
