### ISSUE TITLE
Three Enhancements

### ISSUE THREAD

**Issue by XiaoGeNintendo** [Earthcomputer/EnchantmentCracker#110]
Hi, I've been using this software for a long time and I have two enhancements:

1. Forcibly set player seed as we can do so in the previous versions. Someone told about it already: #97 . This can be easy because you could just add a text box to set it.

2. Some messages like "invalid seed" are displayed only in console but not on screen. This will be confusing to users who are not so familar with the software I think. This can also be easy because you could just create a function like `Log.infoWithDisplay(String info)` and call it necessarily.

3. Program will not throw any exception or show any warning message when the user tries to crack enchantment without getting a player seed. This can be solved easily too by simply adding an 'if' sentence.

Hope you'd accept it. :)

**Comment by Earthcomputer** [comment]
Hello, please could you split these into separate issues as it's easier to keep track of them that way. There is no need to create a new issue for the first one as there is already an issue for it.
