### ISSUE TITLE
can't open EnchCracker

### ISSUE THREAD

**Issue by Violettaa** [Earthcomputer/EnchantmentCracker#112]
hi, I'm trying to open up the EnchCracker program (enchcracker.bat) and it just opens command prompt as shown in the following image.
 
![image](https://user-images.githubusercontent.com/54690855/63982495-5ad85200-ca88-11e9-96f9-f411c6719bd9.png)

I know RAM isn't the issue, since i  have almost 16 gigs and almost all of them are available (15.9 GB). I have installed Java, and I'm almost certain it's 64-bit. I've tried googling how to make sure Java is in my PATH and nothing seems to have helped, and I don't know what else would be the reason for why the program won't launch. 

Thank you in advance!

**Comment by MCRcortex** [comment]
Would you mined checking if java is 64 bit?
This may be the issue

**Comment by hube12** [comment]
just run `java -version`

**Comment by hube12** [comment]
https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239858_230deb18db3e4014bb8e3e8324f81b43

**Comment by Violettaa** [comment]
Oh! Thank you so much for that link, it's working now!
