### ISSUE TITLE
Bedrock request

### ISSUE THREAD

**Issue by noodlychezzy** [Earthcomputer/EnchantmentCracker#113]
If you could find a way to make this compatible with the bedrock edition, it would be awesome, but I've heard that there isn't enough info yet.
Bedrock and java are both minecraft, i dont get why mojang doesn't want them to be the same thing

**Comment by Earthcomputer** [comment]
It won't be feasible on Bedrock edition. It may be feasible to crack the XP seed, but actually manipulating the enchantments requires cracking the RNG which generates the XP seeds. Java edition uses a Linear Congruential Generator for its random numbers, but Bedrock uses a Mersenne Twister which are harder to reverse. In context, that means you may end up doing hundreds of dummy enchants before getting anything useful out of it.

**Comment by asquared31415** [comment]
624 outputs is the minimum amount of information that can determine the exact state of a Mersenne Twister.  At 45 outputs visible without doing a dummy enchant to get more info, that’s 14 dummy enchants to get the state.  Still a pain, but perhaps not that infeasible.

**Comment by Earthcomputer** [comment]
It might be less than 624 if we find a smarter way of doing it. There is a naive method which would require the cracking of 624 XP seeds (and 624 dummy enchantments) before you can do anything, but could make it less. But not anything like 2 as you have for Java edition.
Also it's untrue that the outputs must be aligned with the start of the MT.
