### ISSUE TITLE
Over 100%

### ISSUE THREAD

**Issue by Bobby-McBobface** [Earthcomputer/EnchantmentCracker#115]
![image](https://user-images.githubusercontent.com/54757965/64071771-f00b5e80-ccb3-11e9-9806-d8aa9cdff8be.png)

**Comment by Earthcomputer** [comment]
Can you provide steps to reproduce? The log file (enchcracker.log) would also be helpful.

**Comment by Bobby-McBobface** [comment]
[enchcracker.log ](https://github.com/Earthcomputer/EnchantmentCracker/files/3582869/enchcracker.log)

[Video with slowmo when it happens](https://github.com/Earthcomputer/EnchantmentCracker/files/3582877/Enchantment.Cracker.2019-09-06.15-53-40_Slomo.zip)

**Comment by Bobby-McBobface** [comment]
Sorry for the late reply
