### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by M333r** [Earthcomputer/EnchantmentCracker#116]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3563739/enchcracker.log)

This time I started on 15 for both(2nd time in log) and still got the error(didnt get the error the first time in the log, but got a "fail")

**Comment by Earthcomputer** [comment]
Please update to version 1.4.5 and let me know if this is still an issue.
