### ISSUE TITLE
4 Fails in a row

### ISSUE THREAD

**Issue by M333r** [Earthcomputer/EnchantmentCracker#117]
I am in 1.4.5, I thought it might be my fault but I have had 4 fails in a row(one was on last cracker so isnt in log) I am sure I am doing everything right: enchanting an item, calculation an XP seed, enchanting another item then resetting the cracker, then calculation the next XP seed, but the player seed always fails to be found(also i have mad sure I am not eating/sprinting/gaining XP multiple times. also tried the same numbers on version 1.4

1.4.5 log:
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3563766/enchcracker.log)
, got the same XP seeds, and they still could do calculate the player seed.

1.4 log(I did it in reverse order but just used the same numbers from the 1.4.5 .log file):
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3563768/enchcracker.log)

**Comment by Earthcomputer** [comment]
Try using the mod instead https://github.com/Earthcomputer/clientcommands/releases which gives you more detailed information about what went wrong.
You have to first enable it by running the command `/ctemprule set enchantingPrediction true`, then there is a built-in enchantment cracker which works the same way as this one.
Also run `/ctemprule set playerRNGMaintenance false` for more error-catching.
The mod requires the Fabric mod loader. Install fabric from https://fabricmc.net/use , you also need Fabric API (install it like any other Fabric mod): https://minecraft.curseforge.com/projects/fabric .
Let me know how it goes.

**Comment by Earthcomputer** [comment]
As discussed on discord, this was down to you having a beacon active. We can now close this as resolved.
