### ISSUE TITLE
1.4.5 Ram problem?

### ISSUE THREAD

**Issue by agent4242** [Earthcomputer/EnchantmentCracker#118]
![image](https://user-images.githubusercontent.com/54812108/64124822-fd9e1280-cd9f-11e9-889f-c34e1e481b64.png)

This message pops up even though I have more than 2 gigs free for use... I have no idea...

**Comment by Earthcomputer** [comment]
Please ensure you have 64-bit Java. You can check by typing `java -version` in cmd.

**Comment by hube12** [comment]
https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239858_230deb18db3e4014bb8e3e8324f81b43 to install jre 64bits (without logging to java.com)

**Comment by agent4242** [comment]
Nope I had the right java, I fixed it by lowering the RAM needed to 1 gig... Idk why it works but it does xD

**Comment by agent4242** [comment]
nevermind it says that it is out of memory once i let it check the player seed... should've expected it :P

**Comment by agent4242** [comment]
Ok guess what? I am stupid... I had 64 bit java... Just needed to update it... Sorry for wasting your time...
