### ISSUE TITLE
"Not enough RAM" Error

### ISSUE THREAD

**Issue by SilentStormm** [Earthcomputer/EnchantmentCracker#119]
When i try to run the program i get an error saying "Could not reserve enough space for 2097152KB object heap" even though I'm using only about 60% of my 8GB RAM.

**Comment by MCRcortex** [comment]
The cracker requires 2GB of ram to be available for the program to launch

**Comment by SilentStormm** [comment]
I did close everything (including Minecraft) and it still threw the error

**Comment by hube12** [comment]
EnchantmentCracker/64-bit Java
Please ensure you have 64-bit Java. You can check by typing `java -version` in cmd.
You can use [this link](https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239858_230deb18db3e4014bb8e3e8324f81b43) to install 64-bit Java 8 without having to login to java.com.

**Comment by SilentStormm** [comment]
Yup, I have the latest version of 64-bit Java. Besides, the second latest version of the app works perfectly.

**Comment by Earthcomputer** [comment]
The second-latest version of the app asked for less memory and then sometimes crashed while it was running because it ran out of memory.

**Comment by SilentStormm** [comment]
Yeah, I know, but it works on my computer and the latest version doesn't (also I haven't encountered a crash yet).

**Comment by Earthcomputer** [comment]
This error is thrown by the JVM itself. There are two possible reasons that the error can be thrown. Firstly (and most obviously) you physically don't have enough RAM, or that RAM is being taken up by other programs. But another common reason is that your JVM doesn't support allocating 2GB, and you need to upgrade. This happens, for example, in 32-bit JVMs, so please paste here the output of `java -version` so we can rule that out completely.

**Comment by SilentStormm** [comment]
So apparently i somehow had 32-bit Java installed and that caused the issue. Thanks for help!

**Comment by SilentStormm** [comment]
By the way, can you log out of the server in between cracking the seed?

**Comment by Earthcomputer** [comment]
No

**Comment by SilentStormm** [comment]
and can you pick up the bulk items and redtop them? I got over 28 stacks and don't have that much

**Comment by SilentStormm** [comment]
dammit I took damage, that resets everything too?

**Comment by Earthcomputer** [comment]
Picking up items and re-dropping them is allowed, taking damage resets.
