### ISSUE TITLE
Make this program run online (host  it on website) , and vb.net.

### ISSUE THREAD

**Issue by kabanga0** [Earthcomputer/EnchantmentCracker#121]
I would love to see this program on a website, where we wouldn't have to worry about our pc performances, and that'll be quick and simple i think, i also need to know if am allowed to recrate this program using vb.net language, as this will increase performance on widows and will run much faster when written in vb.net, thank you.

**Comment by Earthcomputer** [comment]
This software is under the MIT license, so of course you can do whatever you want with this code, including rewrite it in other languages and host it yourself on a website. I won't help or host it myself, though, I'm afraid I don't have the time or money for that.
