### ISSUE TITLE
enchantment cracker not working

### ISSUE THREAD

**Issue by KomVechtenDan** [Earthcomputer/EnchantmentCracker#123]
hi, i downloaded the latest release of your enchantment cracker but when i tried to open the enchcracker batch file it opend the windows system screen (black screen with white tekst and it told me that it couldn't launge because it didn't have enough space but the only thing that i have downloaded on this laptop is minecraft, optifine and forge. can you please tell me what to do?
(btw i'm using windows)

**Comment by KomVechtenDan** [comment]
![image](https://user-images.githubusercontent.com/57621712/68581562-ed2da680-0478-11ea-88f0-37db8eb2ad39.png)

**Comment by KomVechtenDan** [comment]
nvm i had the wrong java version

**Comment by Earthcomputer** [comment]
Sometimes it helps to read the error message, or search for already-created issues on GitHub.
