### ISSUE TITLE
Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by DushBig** [Earthcomputer/EnchantmentCracker#125]
I can't launch it due to this- 
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is recommended for enchcracker.
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

I have no idea what to do to resolve this.

I have 16GB of ram so I don't feel as if my RAM is the problem. If it is then how do I allocate more to launch this?

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by DushBig** [comment]
I uninstalled java, reinstalled java, Deleted older versions, restarted my computer, I have no idea why it's still prompting me with the same issue about not enough memory. Are there further instructions to fixing this that I'm unaware of?

**Comment by DushBig** [comment]
I resolved the issue, for some reason Minecraft was set to use 6GB of RAM and I had 32 Bit instead of 64 installed. It is working perfectly fine now, Thank you for your time.
