### ISSUE TITLE
Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by crazytaj** [Earthcomputer/EnchantmentCracker#127]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

I have well over 2gb of RAM available, and I just installed Java 64bit. I do not know what else to try.

**Comment by Earthcomputer** [comment]
Can you run `java -version` just to check that it is using 64-bit Java?

**Comment by crazytaj** [comment]
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)

thats the output

**Comment by Earthcomputer** [comment]
That output does not contain "64-Bit", therefore you are still running 32-bit Java. To change it so Windows uses your 64-bit Java version, you need to [change the PATH variable](https://www.java.com/en/download/help/path.xml). Also, here's a useful [link](https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239858_230deb18db3e4014bb8e3e8324f81b43) to a 64-bit Java 8 version.

**Comment by crazytaj** [comment]
Thanks for your help, after getting java to 64bit it worked flawlessly!
