### ISSUE TITLE
Implementing on a server

### ISSUE THREAD

**Issue by crazytaj** [Earthcomputer/EnchantmentCracker#128]
I think this would be a useful tool to have on a website of some sort, and I would like to try and host it for me and some friends, but I can't get it to run properly. Any advice on how to go about this would be very helpful.

**Comment by Earthcomputer** [comment]
My main issue is that I don't have a server to host it on - my website is hosted on GitHub pages. I could still write it in JavaScript, but the way it currently works means that a direct translation to JavaScript will make it too slow. I have been thinking for some time about a more mathematical way to crack the seed which won't take nearly as long, or as much memory, but no real breakthroughs so far.
