### ISSUE TITLE
No player seed found on 1.15 server

### ISSUE THREAD

**Issue by throwaway1231** [Earthcomputer/EnchantmentCracker#129]
I'm using enchcracker v1.4.6 on a 1.15.2 mostly vanila server. the owner told me he has almost no plugins, and non related to enchanting. I can find the 2 enchanting seeds, just not the player seed.
I've
-confirmed that I'm not in beacon range, and that I haven't done anything on the "to-avoid" list
-pretty sure that I haven't inputted anything incorrectly, looking as I've tried 3 times already
-tried the fabric mod, the mod did not catch any issues either but the player seed was not cracked.

**Comment by Earthcomputer** [comment]
Is the server running PaperMC? PaperMC breaks it.

**Comment by Earthcomputer** [comment]
It's been 6 days and you haven't responded, so I'm assuming you solved the issue. If you haven't please reply and I'll reopen.

**Comment by tangpipi** [comment]
> It's been 6 days and you haven't responded, so I'm assuming you solved the issue. If you haven't please reply and I'll reopen.

Could you tell me how to fix it on PaperMC,and i'm the owner of it.
thx

**Comment by Earthcomputer** [comment]
The only way is to uninstall PaperMC.
