### ISSUE TITLE
Native library not loaded on Mac OS

### ISSUE THREAD

**Issue by snokec** [Earthcomputer/EnchantmentCracker#13]
Have tried versions 1.0.1 - 1.1.2. 1.0.1 is the only version that successfully launches, but gives `Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path` when hitting _Add Info_.

All other versions from 1.1 -> 1.1.2 fail to launch and give different errors depending on the version. Latest version 1.1.2 gives `java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path` when executing the sh script, pops up a Java window with `Probably cause: The library file could not be found.` with a suggestion to post an issue here. Here are the contents of my enchcracker.log:

```[2018-04-11 02:11:07] [/INFO]: System details:
[2018-04-11 02:11:07] [/INFO]: OS = Mac OS X 10.11.6
[2018-04-11 02:11:07] [/INFO]: Arch (either OS/Java) = x86_64
[2018-04-11 02:11:07] [/INFO]: Java = 1.8.0_162
[2018-04-11 02:11:07] [/INFO]: Java arch = 64
[2018-04-11 02:11:07] [/SEVERE]: Failed to load native enchcracker library!
java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:59)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:104)

**Comment by Earthcomputer** [comment]
A lot of people on Mac OS have told me this is an issue. I don't own a mac, so I haven't been able to test it yet. But I will get a virtual machine today to see if I can reproduce it on there.

**Comment by Earthcomputer** [comment]
I asked a friend to borrow their Mac (because you need a Mac to obtain a Mac OS ISO for the virtual machine), but they're on holiday atm so you'll have to wait until next Tuesday until I can get a native XP seed cracker working for Mac OS.
In the mean time, I'll re-implement the XP seed cracker in Java, which is likely to run a little slower, but is better than nothing for the time being.

**Comment by snokec** [comment]
Much appreciated and thanks for releasing such a helpful utility

**Comment by Earthcomputer** [comment]
Version 1.1.3 contains the temporary Java fix. It is noticeably slower than the native version, but it'll have to do for now.

**Comment by Earthcomputer** [comment]
After much research on the topic I have decided that native Mac OS libraries will not be officially supported. I do not own a Mac and don't ever plan to, so there.
Mac users can use the Java version of the cracker, or switch to Windows or Linux if they want a (~6x) faster cracker. Tech-savvy Mac users can also compile their own dynamic libraries from `natives/src` in this repository.
