### ISSUE TITLE
Not loading the program

### ISSUE THREAD

**Issue by MinersOP** [Earthcomputer/EnchantmentCracker#131]
"Could not reserve enough space for 2097152KB object heap" this keeps popping up

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by MinersOP** [comment]
so it did not fix the said issue is there anything else

**Comment by Earthcomputer** [comment]
Please post here the output of `java -version`.

**Comment by MinersOP** [comment]
nvm i got it
it was java but the link you sent i think was outdated.

**Comment by Earthcomputer** [comment]
The link I sent was not outdated, you must have set it up wrong.
