### ISSUE TITLE
Problems starting the program. 

### ISSUE THREAD

**Issue by giacoro** [Earthcomputer/EnchantmentCracker#132]
The file I launched gave me some errors about which version of java I had installed and how much RAM I had on my PC. But it seems to me to have the perfect conditions to start the program

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by giacoro** [comment]
Java version 1.8.0_241

**Comment by giacoro** [comment]
I did that and it says the same thing: [Image](https://imgur.com/a/OUfFTUC)

**Comment by Earthcomputer** [comment]
Can you paste the full output of `java -version`?

**Comment by giacoro** [comment]
[Output](https://imgur.com/a/Y5p3hyo)

**Comment by Earthcomputer** [comment]
As you can see, that doesn't say that your Java version is 64-bit; therefore you are running 32-bit. Please install 64-bit Java properly and try again.

**Comment by giacoro** [comment]
Did it, the`java -version` message is the same.

**Comment by Earthcomputer** [comment]
You may need to change your PATH variable to point to your new Java installation.

**Comment by giacoro** [comment]
> You may need to change your PATH variable to point to your new Java installation.

how should i do this ?

**Comment by Earthcomputer** [comment]
This is a good guide (although you probably don't need to keep your old Java version in the PATH)
https://stackoverflow.com/a/47469319

**Comment by Earthcomputer** [comment]
You only need to follow steps 1-4

**Comment by giacoro** [comment]
Don <img width="674" alt="cmd 2" src="https://user-images.githubusercontent.com/60732368/73934606-14acd780-48df-11ea-8548-161f099d2112.png">

**Comment by Earthcomputer** [comment]
Great - it should work now

**Comment by giacoro** [comment]
<img width="674" alt="cmd 3" src="https://user-images.githubusercontent.com/60732368/73934717-4de54780-48df-11ea-9e7d-ba1e85358a5e.png">

**Comment by giacoro** [comment]
nope

**Comment by giacoro** [comment]
I shut down the computer to make sure it wasn't an error but it seems to happen again

**Comment by Earthcomputer** [comment]
Hmm, try removing special characters from the path to the enchantment cracker. Illegal characters include "!", "?" etc. You possibly may need to remove spaces too, although I'm not sure on that one.

**Comment by giacoro** [comment]
Where are these special characters?

**Comment by Earthcomputer** [comment]
For example, you may have put the enchantment cracker in `C:\Users\Admin\Desktop\Enchantment Cracker!!!`, and the exclamation marks are there. I am only guessing - I don't know what you named the folder. The only other things I can think of are that you moved around the files, or didn't extract them into a directory with write permissions.

**Comment by giacoro** [comment]
I try to reinstall this

**Comment by giacoro** [comment]
Now it says Error JAVA_HOME is not set and no Java command could be found in your path

**Comment by Earthcomputer** [comment]
What did you set your JAVA_HOME and PATH to?

**Comment by giacoro** [comment]
path C:\Program Files (x86)\Common Files\Oracle\Java\javapath

**Comment by giacoro** [comment]
JAVA_HOME not set

**Comment by giacoro** [comment]
JAVA_HOME not set

**Comment by giacoro** [comment]
watch

**Comment by giacoro** [comment]
https://imgur.com/a/v8IslUV

**Comment by giacoro** [comment]
If u want i could give you my anydesk or teamviewer and you can resolve manually because i cant figure out the problem

**Comment by Earthcomputer** [comment]
Remove `\bin` off the end of JAVA_HOME

**Comment by giacoro** [comment]
> Remove `\bin` off the end of JAVA_HOME

also from path?

**Comment by Earthcomputer** [comment]
Nope, keep it in PATH

**Comment by giacoro** [comment]
ok, now when i type in cmd java -version it says no command matching java

**Comment by giacoro** [comment]
It is a mess. Can you please come in my anydesk?

**Comment by Earthcomputer** [comment]
No, I don't have time for that right now.

**Comment by giacoro** [comment]
by the way it says 64 bit in cmd. but now it says "impossbile trovare o caricare la classe principale enchcracker.enchcrackerwindow"

**Comment by giacoro** [comment]
the enchcracker.enchcrackerwindow main class could not be found or loaded

**Comment by giacoro** [comment]
In the jar file there is only manifest.me not main.class. Maybe now this is the problem

**Comment by Earthcomputer** [comment]
That should be okay since the bat file specifies the main class on the command line

**Comment by giacoro** [comment]
and then why does it not work?

**Comment by Earthcomputer** [comment]
Not sure, it's weird, and I haven't seen anyone else with this problem.
Try running `set JAVA_OPTS=-Xdiag` in the command prompt before running the batch script again from the same prompt. This should output some diagnostic information which you should send me. If there's a lot, it may be good to copy paste it and put it on a site like pastebin.

**Comment by giacoro** [comment]
doesnt say anything

**Comment by Earthcomputer** [comment]
What

**Comment by Earthcomputer** [comment]
Does it work if you run it directly?
1. open command prompt in the `lib` directory
1. Run `java -Xms2g -Xmx2g -cp enchcracker-1.4.6.jar enchcracker.EnchCrackerWindow`

**Comment by giacoro** [comment]
the .jar doesnt open
it opens meta inf ecc...

**Comment by Earthcomputer** [comment]
Can you post a screenshot of the exact output

**Comment by giacoro** [comment]
by the way in command promt it says impossible to find enchcracker.EnchCrackerWindows
<img width="674" alt="aaa" src="https://user-images.githubusercontent.com/60732368/73946451-3cf40080-48f6-11ea-8f99-3f1f8bbb38ad.png">

**Comment by giacoro** [comment]
> Does it work if you run it directly?
> 
> 1. open command prompt in the `lib` directory
I didn't did it btw

**Comment by Earthcomputer** [comment]
You need to open the program from the correct directory. Open the batch file from the `bin` directory. If that doesn't work, try what I said and open the jar from the `lib` directory.

**Comment by giacoro** [comment]
the jar doesn't open
it opens the zip with metainf data enchcracker

**Comment by Earthcomputer** [comment]
Don't double click the jar, double click the bat.

**Comment by giacoro** [comment]
ok, and do what

**Comment by giacoro** [comment]
man
it works now. Thank you so much for the help.
