### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by aliedyne202** [Earthcomputer/EnchantmentCracker#137]
hmm, idk why but i hve installed my java correctly and setup the path for it, but this app wont run on my device

**Comment by Earthcomputer** [comment]
Please send the error log.

**Comment by aliedyne202** [comment]
![image](https://user-images.githubusercontent.com/55663663/77104156-83d92800-6a56-11ea-9883-5b8cf396dd12.png)

**Comment by aliedyne202** [comment]
ah sorry, my fault, im using jdk as java_home instead of jre, its ok now, i always forgot to switch them

**Comment by Earthcomputer** [comment]
Which jdk and jre versions are you using? I can run it fine with openjdk 1.8.0_242

**Comment by aliedyne202** [comment]
im using open jdk 12, and normal jre from java oracle 1.8.0_241...

**Comment by aliedyne202** [comment]
ah sir, its not a place to asking some q, but sorry i have to ask u about this
is this tool can be used for bukkit or spigot server? coz mos of server now not longer using vanilla

**Comment by Earthcomputer** [comment]
To my knowledge it still works on bukkit and spigot, unless the server has some plugin which breaks it somehow. It does not work on papermc, however.
