### ISSUE TITLE
How do i translate it

### ISSUE THREAD

**Issue by stevensane** [Earthcomputer/EnchantmentCracker#138]
How do I translate this software, I hope I can translate it into my Mandarin because my English is not good and I do n’t like to translate it every time because it ’s very troublesome, please help me thanks

**Comment by Earthcomputer** [comment]
Yes, I definitely can't see a reason why this shouldn't be possible. Currently you can't, but I will make some changes to the code this afternoon so that you can, then I will write some instructions on how you can contribute other languages. Thanks for your willingness to contribute!

**Comment by Earthcomputer** [comment]
@stevensane you should be able to contribute translations now, see the section at the bottom of the readme. Reply if you need any help.

**Comment by Earthcomputer** [comment]
Closing as resolved

**Comment by stevensane** [comment]
Oh no, my laptop was broken two days ago so I did n’t reply, but I now seem to have successfully translated into my native language. How can I replace it with my native language? Please excuse me if there are stupid questions, because I have only recently started using GitHub.

**Comment by Earthcomputer** [comment]
Someone else beat you to it haha: #142 
Feel free to verify that the [Chinese translations](https://github.com/Earthcomputer/EnchantmentCracker/blob/master/resources/i18n/EnchantmentCracker_zh.properties) are correct though, as I can't 100% verify them as I don't speak Chinese.

**Comment by stevensane** [comment]
Oh, I see it. I was defeated haha. It seems that the translation of Simplified Chinese is all right without any errors. Since someone has translated my translation into Traditional Chinese, it should be simpler. Wait for me for three minutes and upload the traditional Chinese translation right away. The calculator you made is also very famous in Taiwan. I think it should become more famous after translation.

**Comment by stevensane** [comment]
I seem to upload to the wrong folder? Sorry
