### ISSUE TITLE
I want it to support 32 bit XP computers.

### ISSUE THREAD

**Issue by DTTX005** [Earthcomputer/EnchantmentCracker#139]
Since I don't have the money to buy a good computer configuration, so has been stuck in XP system 32-bit, I first heard that the software is very happy. But I tried it and found it didn't support 32-digit computers, so I was hoping it would.

**Comment by Earthcomputer** [comment]
32-bit will not be supported, because Java limits the memory available to 32-bit programs to lower than the requirements of the enchantment cracker. This in combination with how old 32-bit computers are, means I will not support it.
