### ISSUE TITLE
Enchantment cracker crashes on open

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/EnchantmentCracker#14]
No log file, no error message.

**Comment by Earthcomputer** [comment]
What's the value of `%errorlevel%` after you run the jar file from the command line?

**Comment by OreoLamp** [comment]
It doesnt happen anymore, but i got literally nothing. I just put in the arguments, it looked like it didnt even start, i would not have noticed that it started unless it wouldnt have popped up on screen, and just exited back to the folder

**Comment by Earthcomputer** [comment]
I really can't see anything that would cause the program to exit on the Java side without an error message. Maybe something on the C++ side? I could imagine an `std::bad_alloc` causing this. I calculated that the native code needs about 269MB of RAM to do its XP seed cracking (not including all the RAM the JVM and the Java end needs), so maybe it's caused by native code running out of memory.

I'll see what I can do in terms of improving error messages later. For now just make sure you have enough free RAM and let me know if it still occurs. If it still doesn't work try deleting `enchcracker.dll` and see what happens.

**Comment by Earthcomputer** [comment]
Native error messages added in version 1.1.4, which will come out next week. Since there's nothing I can really do to reduce the memory usage (other than warn the user) I'm going to close this now.
