### ISSUE TITLE
Can not downlaod

### ISSUE THREAD

**Issue by CreeperHK** [Earthcomputer/EnchantmentCracker#141]
"Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!"

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by skps00** [comment]
I have to same problem too. But, after I change the environment variables, it still can't use. I am using
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Comment by aaronhendy** [comment]
Havent used this software before so no clue what to do, where do I run 'java -version'?

**Comment by aaronhendy** [comment]
java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode)

**Comment by Earthcomputer** [comment]
As you can see, your Java does not say it is 64-bit, therefore it is 32-bit

**Comment by Earthcomputer** [comment]
?template stale
