### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by FredLin5** [Earthcomputer/EnchantmentCracker#142]
This project is so cool! Thank you for coding this!
I am a Chinese and I want to translate it so it can be easily used by more Chinese users. 
Here's simplified Chinese translation file for EnchantmentCracker. 
[EnchantmentCracker_zh_CHS.properties.zip](https://github.com/Earthcomputer/EnchantmentCracker/files/4396762/EnchantmentCracker_zh_CHS.properties.zip)

**Comment by Earthcomputer** [comment]
Thank you!

**Comment by FredLin5** [comment]
Seems like there's some errors in my translation, so I updated it and translated the About tab. Here it is.

[EnchantmentCracker_zh.properties.zip](https://github.com/Earthcomputer/EnchantmentCracker/files/5653629/EnchantmentCracker_zh.properties.zip)
