### ISSUE TITLE
Can't calculate seed

### ISSUE THREAD

**Issue by PiauTW** [Earthcomputer/EnchantmentCracker#143]
XP seed 1: A16C6C35
XP seed 2: B6A01221
version 1.15.2

**Comment by PiauTW** [comment]
![image](https://user-images.githubusercontent.com/46679502/77844795-0773e100-71dc-11ea-8db6-22184e439de8.png)

**Comment by Earthcomputer** [comment]
?template failed

**Comment by PiauTW** [comment]
thx
