### ISSUE TITLE
Enchants doesn't work properly

### ISSUE THREAD

**Issue by domek16** [Earthcomputer/EnchantmentCracker#144]
Hello there, I spent almost all day trying your program. I even tried earlier versions of it. It seems not to work (checked 1.14.4, 1.8, 1.12.2). I did everything that you showed on youtube and I didn't do anything wrong like sprinting etc. If you can find a while for me, please contact :). I even can record a video on how I do it.

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Earthcomputer** [comment]
?template stale
