### ISSUE TITLE
Could not reserve enough space for 2097152KB object heap(I have read the other two)

### ISSUE THREAD

**Issue by jameshuang666** [Earthcomputer/EnchantmentCracker#147]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
I have read the other two who have the same problem.
I have 2.8G of RAM and I used your link for 64bit java
but then I run java -version in cmd and got this:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode)
I still didn't get 64bit java,why?(I used your link for 64bit java)

**Comment by Earthcomputer** [comment]
You may need to change your Java path. The following message will contain instructions to do that

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by jameshuang666** [comment]
thank you.
I'm working on it now,just wait and see

**Comment by Earthcomputer** [comment]
?template stale
