### ISSUE TITLE
Fail to open enchcracker

### ISSUE THREAD

**Issue by hueyte** [Earthcomputer/EnchantmentCracker#148]
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jre1.8.0_221\bin
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by hueyte** [comment]
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode, sharing)

**Comment by hueyte** [comment]
I've changed the environment variables also.

**Comment by hueyte** [comment]
![System Properties 07_04_2020 11_25_40](https://user-images.githubusercontent.com/63274417/78626896-ad050f80-78c2-11ea-8545-f66f9b9d9f81.png)

**Comment by hueyte** [comment]
![System Properties 07_04_2020 11_27_24](https://user-images.githubusercontent.com/63274417/78626929-c7d78400-78c2-11ea-9fcd-5fb534d47cc3.png)

**Comment by hueyte** [comment]
okay, I solved it by changing C:\Program Files\Java\jre1.8.0_221\bin becomeC:\Program Files\Java\jre1.8.0_221
