### ISSUE TITLE
Not working in java 1.15.2

### ISSUE THREAD

**Issue by Stehsaer** [Earthcomputer/EnchantmentCracker#149]
the cracker can't work in java 1.15.2. i'm sure that i didn't do anything not allowed.
I can both get 2 seeds but when i click 'calculate seed' it said fail. i simply forgot to take a screenshot. is 1.15.2 not supported yet?

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Earthcomputer** [comment]
?template stale

**Comment by jw910731** [comment]
I had the same problem with Minecraft 1.15.2 paper server.
The program says that it can't calculate the player seed. Even I had gone through all of the process and didn't do those disallowed actions during the seed calculating process.

**Comment by Earthcomputer** [comment]
?template modded
