### ISSUE TITLE
Work on paper1.15.2

### ISSUE THREAD

**Issue by Dmitri233** [Earthcomputer/EnchantmentCracker#151]
I tried it on the old release of paper. He does not work. But I updated the paper to the current # 165 release. He worked. Maybe I think this is the problem of paper.Or how to prevent players from using EnchantmentCracker.

**Comment by Earthcomputer** [comment]
?template modded

**Comment by Dmitri233** [comment]
I'm wrong. He always works on paper. I want to stop it from working.
