### ISSUE TITLE
Not working in snapshot versions

### ISSUE THREAD

**Issue by TheDarkAndroid** [Earthcomputer/EnchantmentCracker#152]
I know this is probably to be expected but I didn't see an issue about this so I'll open one.

**Comment by TheDarkAndroid** [comment]
Also I have no clue how to add labels

**Comment by Earthcomputer** [comment]
Duplicate of #133, although the necessary changes for 1.16 so far have been implemented, and you can use it if you compile from source. I only create releases for full releases, and I explain the reasoning in the linked issue.

Adding labels is something most users don't have permission to do, sorry!

**Comment by TheDarkAndroid** [comment]
How can I compile from source?

**Comment by Earthcomputer** [comment]
Follow the "building from source" section in the readme.

**Comment by TheDarkAndroid** [comment]
![image](https://user-images.githubusercontent.com/20667076/79008028-c923dd80-7b5c-11ea-9118-af65ee0dfffe.png)
This is what happens

**Comment by Earthcomputer** [comment]
Oh, right, I need to update gradle then. In the mean time, you can compile it with jdk8.

**Comment by TheDarkAndroid** [comment]
I set the JAVA_HOME, but how do I compile?

**Comment by Earthcomputer** [comment]
Just run `gradlew build`

**Comment by TheDarkAndroid** [comment]
Again, the same "Could not determine java version from '14'" error

**Comment by Earthcomputer** [comment]
Ah, sod it! I updated Gradle for you, so it should now recognize your Java 14 installation.
- Run `git pull` to get the up-to-date version of the repository.
- Try `gradlew build` again after that.

**Comment by TheDarkAndroid** [comment]
Ok, I built it, thanks and sorry for bothering you

**Comment by TheDarkAndroid** [comment]
Also, I've done this 3 times now, there's always something missing from what I've tried to enchant.

**Comment by TheDarkAndroid** [comment]
In particular Looting and Sweeping Edge were missing on both of the 2 swords (1 netherite and 1 diamond) that I enchanted.

**Comment by Earthcomputer** [comment]
It might be better to create a new issue to track that, and I will try and reproduce your issue, thanks

**Comment by Earthcomputer** [comment]
@TheDarkAndroid you must have done something wrong. I just tried it out on the latest snapshot (20w15a), and succesfully enchanted both a netherite and diamond sword with looting 3, sweeping edge 3 and sharpness 4.

**Comment by TheDarkAndroid** [comment]
Hmm, I'll have to try again
