### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by urbda** [Earthcomputer/EnchantmentCracker#153]
Everytime I try to open the file it opens a console. This console says, "Could not reserve enough space for 2097152KB object heap."
I've uninstalled and reinstalled Java- the latest version of it in 64-bit. I've checked my storage, and I have enough space. I checked how much ram I have devoted to the programs I run and I have enough ram. I don't know what the problem is. If you could help me, this would be much appreciated because it seems like a really helpful thing for enchanting. Thanks!

**Comment by Earthcomputer** [comment]
You may have thought you installed 64-bit Java but didn't actually potentially? The bot will tell you how to check

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by urbda** [comment]
Thank you! It installed correctly!
