### ISSUE TITLE
Calculate fail in 1.14.3 sever

### ISSUE THREAD

**Issue by NANORY5** [Earthcomputer/EnchantmentCracker#157]
The sever in 1.14.3 can't use it
Always shows fail in calculate
35AE0B1F
D60F9A8F
fail
i try it more than ten times

**Comment by NANORY5** [comment]
The game in 1.15.2 can use it :)

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Earthcomputer** [comment]
?template stale
