### ISSUE TITLE
I cannot open the guide for changing the java path

### ISSUE THREAD

**Issue by jameshuang666** [Earthcomputer/EnchantmentCracker#158]
See the title.

**Comment by jameshuang666** [comment]
I don't understand the guide for changing the java path,also I can't open the link in it.

**Comment by jameshuang666** [comment]
I mean I can't open the link in the guide page

**Comment by Earthcomputer** [comment]
What link? I tested them all and they work fine.

**Comment by Earthcomputer** [comment]
?template stale
