### ISSUE TITLE
enchcracker.bat not launching launching

### ISSUE THREAD

**Issue by BudEBoy** [Earthcomputer/EnchantmentCracker#16]
When I launch enchcracker.bat and error message comes up saying "Windows cannot find 'javaw'. Make sure you typed the name correctly, and then try again."

Is this because i am using windows 7 and not windows 10? If it is a problem with me using windows 7, could we get it to work for windows 7?

**Comment by Earthcomputer** [comment]
Hi,

The program has been tested on Windows 7 and works. The problem is your Java installation. Try reinstalling Java. If that doesn't work, try Googling the problem, you should get plenty of results since it affects most Java programs.

**Comment by BudEBoy** [comment]
thank you for getting back to me, i will try that
