### ISSUE TITLE
The 1.4.6 download will say no files found

### ISSUE THREAD

**Issue by KartoffelBreiP** [Earthcomputer/EnchantmentCracker#160]
hey i can't download the enchcracker 1.4.6 because there is no files found.

Pls help!!

**Comment by Earthcomputer** [comment]
Please can you send a screenshot of the actual error

**Comment by KartoffelBreiP** [comment]
![2020-04-22 (2)](https://user-images.githubusercontent.com/64152981/80012011-f2355e00-84cc-11ea-846d-00bef0a7b951.png)

sry if it's the false translate i'm from Germany
:)

**Comment by Earthcomputer** [comment]
This looks like a browser/OS issue and not an issue with the enchantment cracker.

**Comment by KartoffelBreiP** [comment]
ok can you pls help me to fix it ?

**Comment by KartoffelBreiP** [comment]
because i tried it with some other browsers and it will not work i have no plan why.

**Comment by Earthcomputer** [comment]
I have no idea, there is something wrong with your system. Check that you have permission to access your downloads folder.

**Comment by Earthcomputer** [comment]
?template stale
