### ISSUE TITLE
Failed To Launch Enchcracker

### ISSUE THREAD

**Issue by RutgerSchep** [Earthcomputer/EnchantmentCracker#163]
When I open the enchcracker.bat folder it says 'Failed To Launch Enchcracker!' I meet the requirements that are shown but it still says it failed. Can someone help me?

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by RutgerSchep** [comment]
I have 64 bit java

**Comment by Earthcomputer** [comment]
> If this doesn't work, paste the output of `java -version` here so we know that you have tried it.

**Comment by RutgerSchep** [comment]
![IMG-2689](https://user-images.githubusercontent.com/65067403/81469698-beee1100-91e6-11ea-9a8a-344a1dc44583.jpg)

**Comment by Earthcomputer** [comment]
Uh, that is not a screenshot of the `java -version` command.

**Comment by RutgerSchep** [comment]
How do I use that command

**Comment by Earthcomputer** [comment]
Open the command prompt by pressing the windows key + R, typing "cmd" and pressing enter. In the prompt that comes up, type "java -version" and press enter, send a screenshot of the output.
![image](https://user-images.githubusercontent.com/13084089/81469764-d1644c80-91de-11ea-802e-3f54addb4bc6.png)

**Comment by RutgerSchep** [comment]
![IMG-2690](https://user-images.githubusercontent.com/65067403/81469862-b77b3780-91e7-11ea-8a74-45875153c9a1.jpg)

**Comment by RutgerSchep** [comment]
like this?

**Comment by MCRcortex** [comment]
How much ram do you have free/available

**Comment by Earthcomputer** [comment]
Alright, thanks for verifying you have 64-bit Java (I had to verify because most people who come here have 32-bit).
Maybe try closing some other programs to free up memory?

**Comment by RutgerSchep** [comment]
i'll try that

**Comment by Earthcomputer** [comment]
If that doesn't work, mind send a screenshot of the original error? In case it isn't what I think it is.

**Comment by Earthcomputer** [comment]
?template stale

**Comment by good131210** [comment]
i have a progrem here:
Why i run "enchcracker.bat" it's said -> ERROR: JAVA_HOME is set to an invalid directory
Anyone help me?

**Comment by good131210** [comment]
![image](https://github.com/user-attachments/assets/ef599ac2-6e37-4ed1-9db4-c8196e0f2dec)

**Comment by Earthcomputer** [comment]
@good131210 don't hijack existing 4-year-old issues. Instead better to join the discord to get support.
