### ISSUE TITLE
Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by soloerror650** [Earthcomputer/EnchantmentCracker#165]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

c:\>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

**Comment by soloerror650** [comment]
ok nvm, i use the link and install a new java

**Comment by Mr-Wolf23** [comment]
Hello soloerror650,
I tried to install the EnchantmentCracker and ran into the same problem as you, I was just wondering if you could tell me how you solved your issue.

**Comment by uwuplant** [comment]
Make sure you have 64-bit Java installed. 32-bit Java will not work with this.
