### ISSUE TITLE
I solved the first issue of java not being on the right path but now it is giving me this message :Error: Could not find or load main class enchcracker.EnchCrackerWindow Caused by: java.lang.ClassNotFoundException: enchcracker.EnchCrackerWindow

### ISSUE THREAD

**Issue by Dewnl** [Earthcomputer/EnchantmentCracker#166]
Error: Could not find or load main class enchcracker.EnchCrackerWindow
Caused by: java.lang.ClassNotFoundException: enchcracker.EnchCrackerWindow

**Comment by Earthcomputer** [comment]
No idea, make sure you extracted it correctly and didn't move any files around. Make sure you extracted it to somewhere you have permission.
