### ISSUE TITLE
I don't konw what happened ? Enchantment cracker didn't work. 

### ISSUE THREAD

**Issue by MikoLee2333** [Earthcomputer/EnchantmentCracker#167]
MC version 1.14.4
 Enchantment cracker log
![image](https://user-images.githubusercontent.com/43770943/82759481-52972280-9e20-11ea-99df-563f9b2af913.png)

anyone can help me ? plz !

**Comment by MikoLee2333** [comment]
i m totally follow the Tutorials

**Comment by MCRcortex** [comment]
if your on a "modded" server it will not work, please check that the server is not paper mc or similar

**Comment by MikoLee2333** [comment]
so this just worked in a "pure" game or server？

---Original---

**Comment by MCRcortex** [comment]
Some mods break it (like paper mc) and thus the cracker cannot work on them

**Comment by MCRcortex** [comment]
?template modded

**Comment by MikoLee2333** [comment]
ok，i got the reason
thx for ur reply.



---Original---

**Comment by MikoLee2333** [comment]
i got the reason，it's a modded server by my friend.
thx for ur reply.



---Original---

**Comment by GamerKINGplays** [comment]
I wanted to test this mod on servers but it didn't work on paper server is there any way to fix it so it works on any server

**Comment by ImUrX** [comment]
Using a version of Paper that doesn’t change the RNG (RNGPaper) or Purpur with the RNG patch disabled. Aside from that, there is no other way
