### ISSUE TITLE
New version for 1.15.2?

### ISSUE THREAD

**Issue by kodzisan** [Earthcomputer/EnchantmentCracker#168]
If i use enchcracker for 1.15.2 i get information about fail during calculating seed

**Comment by MCRcortex** [comment]
are you on a modded server/non vanilla in any way server?

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Earthcomputer** [comment]
I should update that message to include a section about modded servers.

**Comment by kodzisan** [comment]
Im using on singleplayer vanilla 1.15.2. Is version for 1.15 working on 1.15.2? Thats may be caused by auto sprint

**Comment by Earthcomputer** [comment]
Sprinting breaks it. Please try again without sprinting.

**Comment by kodzisan** [comment]
http://prntscr.com/soldab anyway it doesnt working for me

**Comment by Earthcomputer** [comment]
Double check the disallowed list again, then try following the rest of the instructions of the bot

**Comment by kodzisan** [comment]
Are you certain that it works on 1.15.2?

**Comment by MCRcortex** [comment]
yes

**Comment by Earthcomputer** [comment]
?template stale
