### ISSUE TITLE
Assistance in making 1.4.6, snapshot compatible

### ISSUE THREAD

**Issue by Rolandsteele** [Earthcomputer/EnchantmentCracker#169]
I'm a bit lost on how I would go about retrofitting 1.4.6 ench. cracker to suit my needs on the latest snapshot. I did reference the build from source instruction in the readme, but it says unable to build, and I'm unsure if my set up is correct for me to accomplish this task.

**Comment by Earthcomputer** [comment]
Hi. the source code has already been updated to work for the snapshots.

**Comment by Earthcomputer** [comment]
I've just realized you probably just wanted to build it and not edit the source. In which case can you send me the actual error message?

**Comment by Rolandsteele** [comment]
Yeah, but just to clarify, are you saying that if I take the 1.4.6 ver. to a latest snapshot server, it should work?

**Comment by Earthcomputer** [comment]
No, only the source code is updated. Once 1.16 is released I will bump the version to 1.5 and publish a build.

**Comment by Rolandsteele** [comment]
Ah, noted. Well in that case I am probably a little too inexperienced all in all to try and work something into a snapshot.
