### ISSUE TITLE
EnchCracker Player Seed Not Found

### ISSUE THREAD

**Issue by Crumbletheundead** [Earthcomputer/EnchantmentCracker#17]
The program used to work, and after entering the End it no longer does. The same issue has been raised before, but no conclusive solution has been posted.

I can get two xp seeds, but when I'm trying to calculate the player seed it says player seed not found. Repeated the process three times thinking I must've entered something wrong, All three repeated attempts failed to yield a player seed. I'm pretty sure I did all three attempts correct since I have written a step-by-step instruction for myself and these instructions have been successful 12 other times before I entered the End.  

In addition, the xp seeds were far easier to attain than before, which might give some insight to why the cracker is no longer working. 

This world is also a minecraft realms world if that helps. I tried recreating the issue in a singleplayer world, but the program worked perfectly in singleplayer (even after I entered the End). 

Log below: 

> [2018-05-03 04:55:09] [/INFO]: System details:
> [2018-05-03 04:55:09] [/INFO]: OS = Windows 10 10.0
> [2018-05-03 04:55:09] [/INFO]: Arch (either OS/Java) = amd64
> [2018-05-03 04:55:09] [/INFO]: Java = 1.8.0_151
> [2018-05-03 04:55:09] [/INFO]: Java arch = 64
> [2018-05-03 04:55:22] [/INFO]: Added info, b = 15, s1 = 7, s2 = 16, s3 = 30
> [2018-05-03 04:55:51] [/INFO]: Reduced possible seeds to 50331681
> [2018-05-03 04:56:04] [/INFO]: Added info, b = 14, s1 = 7, s2 = 15, s3 = 28
> [2018-05-03 04:56:04] [/INFO]: Reduced possible seeds to 1275881
> [2018-05-03 04:56:19] [/INFO]: Added info, b = 13, s1 = 7, s2 = 9, s3 = 26
> [2018-05-03 04:56:19] [/INFO]: Reduced possible seeds to 24579
> [2018-05-03 04:56:31] [/INFO]: Added info, b = 12, s1 = 5, s2 = 16, s3 = 24
> [2018-05-03 04:56:31] [/INFO]: Reduced possible seeds to 155
> [2018-05-03 04:56:47] [/INFO]: Added info, b = 9, s1 = 4, s2 = 9, s3 = 19
> [2018-05-03 04:56:47] [/INFO]: Reduced possible seeds to 1
> [2018-05-03 04:56:57] [/INFO]: Reset the cracker
> [2018-05-03 04:57:33] [/INFO]: Added info, b = 15, s1 = 8, s2 = 10, s3 = 30
> [2018-05-03 04:57:58] [/INFO]: Reduced possible seeds to 33029917
> [2018-05-03 04:58:14] [/INFO]: Added info, b = 14, s1 = 8, s2 = 9, s3 = 28
> [2018-05-03 04:58:14] [/INFO]: Reduced possible seeds to 558930
> [2018-05-03 04:58:30] [/INFO]: Added info, b = 13, s1 = 7, s2 = 16, s3 = 26
> [2018-05-03 04:58:30] [/INFO]: Reduced possible seeds to 3843
> [2018-05-03 04:58:45] [/INFO]: Added info, b = 12, s1 = 6, s2 = 10, s3 = 24
> [2018-05-03 04:58:45] [/INFO]: Reduced possible seeds to 65
> [2018-05-03 04:58:59] [/INFO]: Added info, b = 9, s1 = 5, s2 = 11, s3 = 18
> [2018-05-03 04:58:59] [/INFO]: Reduced possible seeds to 12
> [2018-05-03 04:59:13] [/INFO]: Added info, b = 6, s1 = 3, s2 = 9, s3 = 12
> [2018-05-03 04:59:13] [/INFO]: Reduced possible seeds to 5
> [2018-05-03 04:59:25] [/INFO]: Added info, b = 3, s1 = 3, s2 = 5, s3 = 6
> [2018-05-03 04:59:25] [/INFO]: Reduced possible seeds to 3
> [2018-05-03 04:59:56] [/INFO]: Added info, b = 2, s1 = 3, s2 = 5, s3 = 4
> [2018-05-03 04:59:56] [/INFO]: Reduced possible seeds to 1
> [2018-05-03 05:00:03] [/INFO]: Calculating player seed with 5a262a3, a4d96f7c
> [2018-05-03 05:00:03] [/INFO]: No player seed found
> [2018-05-03 05:00:06] [/INFO]: Calculating player seed with 5a262a3, a4d96f7c
> [2018-05-03 05:00:06] [/INFO]: No player seed found
>

**Comment by Earthcomputer** [comment]
Are you at an enderman farm? Are you hitting endermen during the process? Try getting all the XP you need beforehand and let me know if that works.

**Comment by Crumbletheundead** [comment]
I'm enchanting in the overworld in a simple enchantment setup (15 bookshelves, 1 table). Got all the xp I needed from the farm and got back to the overworld. After the first dummy enchant to start the process, I did not sprint, hit mobs, gain xp, wear mending armor, enchant anything other than the dummies, eat, or interact with anything else.

**Comment by Crumbletheundead** [comment]
Just recreated the issue in a singleplayer world. It wasn't entering the End that caused the cracker to stop working, but after using an elytra to fly. Maybe flying with an elytra somehow changes the mechanics to form some unexpected seeds?

**Comment by Earthcomputer** [comment]
The elytra counts as one of the unbreaking items that you can't use during the process. Did you use your elytra at all between the first dummy enchant and the player seed cracking?

**Comment by Crumbletheundead** [comment]
Nope

**Comment by Crumbletheundead** [comment]
Tried to recreate the fix in multiplayer, but didn't work.

**Comment by Earthcomputer** [comment]
The numbers found in the log could not possibly be consecutive. You must be doing something wrong somewhere. In the mean time, since this is not an issue with the cracker itself, I'm going to close this issue.
