### ISSUE TITLE
How to open when downloaded

### ISSUE THREAD

**Issue by Edwin0915** [Earthcomputer/EnchantmentCracker#171]
After I downloaded the file what should I do?
Press what in the file in order to open the app

**Comment by frctionless** [comment]
you need to go in the bin folder and run the .bat file also did you install the code or the relase?

**Comment by Edwin0915** [comment]
> you need to go in the bin folder and run the .bat file also did you install the code or the relase?

There are three folder in the 1.4.6 which one should I download
After I downloaded which file should I rub

**Comment by frctionless** [comment]
the bin folder i think i can check

**Comment by frctionless** [comment]
yes the bin folder

**Comment by Edwin0915** [comment]
![1592155165092](https://user-images.githubusercontent.com/66914393/84599665-360c6a00-ae63-11ea-9a04-6d43259996d4.jpg)

**Comment by frctionless** [comment]
the .zip

**Comment by Edwin0915** [comment]
Which one

**Comment by frctionless** [comment]
you dont need source code

**Comment by frctionless** [comment]
also its easier to do this with client commands
(its way faster too)

**Comment by Edwin0915** [comment]
![1592155248779](https://user-images.githubusercontent.com/66914393/84599689-6c49e980-ae63-11ea-99cf-616574933ac4.jpg)

**Comment by frctionless** [comment]
yes

**Comment by Edwin0915** [comment]
Run the bin?

**Comment by frctionless** [comment]
ans then the bat file

**Comment by frctionless** [comment]
no open the bin folder

**Comment by Edwin0915** [comment]
![1592155341671](https://user-images.githubusercontent.com/66914393/84599709-a1563c00-ae63-11ea-9d2f-c64045e158aa.jpg)

**Comment by frctionless** [comment]
run the bottom one

**Comment by Edwin0915** [comment]
![1592155387579](https://user-images.githubusercontent.com/66914393/84599752-eda17c00-ae63-11ea-9903-8834321000c1.jpg)

**Comment by frctionless** [comment]
ok whats your discord
i can help better there

**Comment by frctionless** [comment]
mine is robertas#0246

**Comment by Edwin0915** [comment]
![1592155648047](https://user-images.githubusercontent.com/66914393/84599807-55f05d80-ae64-11ea-96c1-7198a3b5bcf7.jpg)

**Comment by frctionless** [comment]
oh your pc is just bad

**Comment by frctionless** [comment]
and do you even have java installed

**Comment by Edwin0915** [comment]
It's a surface pro 4

**Comment by frctionless** [comment]
ok then istall java

**Comment by Edwin0915** [comment]
Do I need to open Minecraft

**Comment by frctionless** [comment]
java.com/en/

**Comment by frctionless** [comment]
no
install java its what it uses

**Comment by Edwin0915** [comment]
Ok

**Comment by frctionless** [comment]
then look if it runs

**Comment by Whanos** [comment]
?template 64bitjava

**Comment by Earthcomputer** [comment]
?template stale
