### ISSUE TITLE
Respiration 3 not working!!

### ISSUE THREAD

**Issue by Saransh323** [Earthcomputer/EnchantmentCracker#172]
I tried enchanting a diamond helmet with 4 enchantments; I got the other three but not Respiration 3. I then tried getting Respiration 3 on a book but that gave me other random enchantments. I followed the steps exactly as shown. Please fix the problem.

**Comment by Earthcomputer** [comment]
Did you remember to do the dummy enchant between throwing out items and doing your actual enchant?

**Comment by Earthcomputer** [comment]
?template stale

**Comment by Saransh323** [comment]
Yes, I did the dummy enchant, only Respiration 3 was not working

**Comment by Earthcomputer** [comment]
Are you using the latest version of the enchantment cracker? I remember there used to be a bug with respiration that was fixed.

**Comment by Earthcomputer** [comment]
?template stale

**Comment by Saransh323** [comment]
I am using version 1.4.6. That is the version I am having a problem with.
Am I running an old version?

**Comment by OneYellowLemon** [comment]
1.5 is the latest version, maybe try updating

**Comment by Saransh323** [comment]
ok, thanks

**Comment by OneYellowLemon** [comment]
Did it work?
