### ISSUE TITLE
I can't open it

### ISSUE THREAD

**Issue by zhiroxi** [Earthcomputer/EnchantmentCracker#173]
My pc is 12 GB Ram,i have installed the last version of java but it still don’t work.
![5A038919-959E-4DF2-88BC-CBCC50A1DC99](https://user-images.githubusercontent.com/67128539/85081624-bec13800-b1cc-11ea-9dff-bcf1d8ac861b.png)
Any solution?

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by zhiroxi** [comment]
Thank you very much,i have uninstall java first then it worked,I hope you have a good day.
