### ISSUE TITLE
Version 1.4.6 Not Initializing

### ISSUE THREAD

**Issue by RealTheMuffinMen** [Earthcomputer/EnchantmentCracker#174]
When I have installed the suggested version of Java, and tried twice already, I continue to get the error message on startup for version 1.4.6 of this cracker. I extract the files in the .zip folder, then double click the batch file in the bin folder. Getting this error on startup, though. 
![Screenshot (958)](https://user-images.githubusercontent.com/67245285/85237328-e8e84500-b3da-11ea-8152-acfd628d21a6.png)

**Comment by MCRcortex** [comment]
?template 64bitjava

**Comment by RealTheMuffinMen** [comment]
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode, sharing)

**Comment by MCRcortex** [comment]
Please read what it says, "If this command does not specify whether you are using 32-bit or 64-bit, then you are using 32-bit. If you are, use this link to install 64-bit Java, then try running the Enchantment Cracker again."

**Comment by RealTheMuffinMen** [comment]
I tried running it again after installing the 64-bit version of Java and I got the same error on launch

**Comment by MCRcortex** [comment]
yes but if you type "java -version" after 64 bit install, does it say you have 64 bit

**Comment by RealTheMuffinMen** [comment]
This is the output of `java -version` in `cmd` after 64 bit install, and I have 16 GB of ram, most of which are not in use

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode, sharing)

**Comment by MCRcortex** [comment]
yes do what it says

**Comment by RealTheMuffinMen** [comment]
I get this error now:

ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jre1.8.0_221\bin

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

**Comment by RealTheMuffinMen** [comment]
Nevermind, I just figured out how to make it work. Thank you for your help MCRcortex, you've been great through this process. I'm new to this kind of thing, which is why this took so long. Thanks for your help again!
