### ISSUE TITLE
Error with opening program.

### ISSUE THREAD

**Issue by Narwhalz4Fun** [Earthcomputer/EnchantmentCracker#179]
When I try to open the .bat file it the error: "Could not find or load main class enchcracker.EnchCrackerWindow" pops up. What do I do?

**Comment by Earthcomputer** [comment]
Did you download the zip in releases, or the source code?

**Comment by Narwhalz4Fun** [comment]
I downloaded the zip and I use windows.

**Comment by Earthcomputer** [comment]
So you're telling me you have a `bin` and a `lib` folder, and you went in the `bin` folder and clicked `enchcracker.bat`?

**Comment by Narwhalz4Fun** [comment]
yes

**Comment by Earthcomputer** [comment]
What is your java version?

**Comment by Narwhalz4Fun** [comment]
when I check with the command it says 1.8.0_251, it is 64-bit

**Comment by Earthcomputer** [comment]
What directory did you extract the zip to?

**Comment by Narwhalz4Fun** [comment]
I have it in a downloads folder

**Comment by Narwhalz4Fun** [comment]
I moved it to a different folder and it started working.

**Comment by Earthcomputer** [comment]
That is very weird, I guess it must have to do with your permissions in that folder. I'll make a note of this issue so I can help people faster in future.
