### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by SoulForYouth** [Earthcomputer/EnchantmentCracker#181]
![image](https://user-images.githubusercontent.com/68137441/87215589-83003500-c36a-11ea-9792-67780c2c8e0f.png)
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/4906219/enchcracker.log)
What's the problem?

**Comment by Earthcomputer** [comment]
A workaround for now is to start off with the highest number of bookshelves, which reduces the most seeds (so it has to store less seeds in memory)

**Comment by SoulForYouth** [comment]
Thanks

**Comment by SoulForYouth** [comment]
Thanks!

**Comment by 6TNTYeeter9** [comment]
The enchantment cracker said that it doesn't have enough memory after I input the highest amount of bookshelves first. It crashed withing a second and it is just 2% progression. How can I fix this issue?
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/4987692/enchcracker.log)

**Comment by Earthcomputer** [comment]
#233 improved memory usage considerably
