### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Kwincii** [Earthcomputer/EnchantmentCracker#182]
Everytime i start it this is there... I made pictures that proof that i have everything that is written in there
![Issue](https://user-images.githubusercontent.com/68144188/87220049-0026ac80-c361-11ea-9db0-9f26d7830774.JPG)
![64 Bit](https://user-images.githubusercontent.com/68144188/87220059-0a48ab00-c361-11ea-94c7-974a2e2916a2.JPG)
![ram](https://user-images.githubusercontent.com/68144188/87220063-0fa5f580-c361-11ea-8460-d4c81224df13.JPG)
![Java_In_C](https://user-images.githubusercontent.com/68144188/87220064-16346d00-c361-11ea-9c27-6e236f821c36.JPG)

**Comment by MCRcortex** [comment]
this could mean that you just dont have enough ram

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by Earthcomputer** [comment]
As the bot says, **please paste the output of java -version**

**Comment by Kwincii** [comment]
it is working thank you so much

**Comment by Kwincii** [comment]
![image](https://user-images.githubusercontent.com/68144188/87395931-6b1af200-c5b2-11ea-89e5-e44409881381.png)
not everything is working :D

**Comment by Hashem8** [comment]
it keeps telling me failed or as above gives me a seed that is all 0 thanks for your time

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Hashem8** [comment]
do i just drag the client commands folder to the mods folder?

**Comment by Hashem8** [comment]
man thanks alot also your vids are amazing keep doing what you do! but just one last question, if on 1.12.2 it does not work what should i do? because there is no fabric for 1.12.2

**Comment by Earthcomputer** [comment]
Then you have to use the enchantment cracker.

**Comment by IAmAGreenFlamingo** [comment]
I have the same issue. I only have java for 64 bit and I got rid of any instances of the 32 bit version, and I have 4 GB of ram free and the program continues to give me errors.

**Comment by Earthcomputer** [comment]
@IAmAGreenFlamingo please paste the error you are getting and the output of `java -version`

**Comment by Earthcomputer** [comment]
?template stale
