### ISSUE TITLE
not being able to identify the seed

### ISSUE THREAD

**Issue by system69-e** [Earthcomputer/EnchantmentCracker#185]
it identifies both seeds flawlessly, however, when i want to calculate the enchantment seed, it fails 

![image](https://user-images.githubusercontent.com/67830794/87797085-78a8d400-c85f-11ea-9745-4cbe28c995d6.png)

**Comment by system69-e** [comment]
I double checked the numbers from the log and matched them with screen shots i took and the y were right. i am on spigot 1.16.

**Comment by leumasme** [comment]
Spigot or Paperspigot?

**Comment by system69-e** [comment]
plain spigot as far as i am concerned

**Comment by system69-e** [comment]
> Spigot or Paperspigot?

plain spigot as far as i am concerned

**Comment by Earthcomputer** [comment]
?template failed

**Comment by system69-e** [comment]
> First of all, check that you are not on a PaperMC server (which may include various flavours of Spigot). PaperMC is known to break enchantment cracking and will never be supported.
i am gonna try clientcommands right now however, the server is not on PaperMC it is on pure Spigot. I actually am not sure what you mean by "flavours of Spigot" do you mean the forks of Spigot including Spigot itself, or just various forks of it

**Comment by Earthcomputer** [comment]
I mean forks of spigot, and various combinations of plugins. I chose the word "flavour" here as not all users may know what a "fork" is.

**Comment by system69-e** [comment]
> I mean forks of spigot, and various combinations of plugins. I chose the word "flavour" here as not all users may know what a "fork" is.

i see i see. the only plugins on the server are only essential x and some basic plot claiming. I have tried this on another Spigot server on 1.15.2 (the past version) and it was doing fine. i tried clientcommands, i put in a sword to have looting 3 and sharpness 4 and bunch of other enchantments. it kinda worked, but i got looting 2 and sharpness 3. both one level under what i input. i do not know if i should create another issue on the clientcommands github page, but assistance would be appreciateed

**Comment by Earthcomputer** [comment]
they might have an enchantments rebalancing plugin or something. Given you've got it to work on another server, it's probably something with the plugins on this server.

**Comment by Earthcomputer** [comment]
?template modded
