### ISSUE TITLE
Pin EnchantmentCracker Window to Top

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/EnchantmentCracker#192]
It would be nice to be able to pin the EnchantmentCracker window, so that it remains above minecraft (in non-fullscreen at least).
This would make the whole process of enchantment cracking a bit faster and less annoying.

**Comment by Earthcomputer** [comment]
This sounds like a bad idea, it's going to be annoying in most situations and not helpful. Maybe a config option instead.

**Comment by leumasme** [comment]
That's what i ment by
> be able to
You could have a pin/unpin button next to the close button for example.

**Comment by Earthcomputer** [comment]
#240
