### ISSUE TITLE
Can't find Java

### ISSUE THREAD

**Issue by rinwectebu** [Earthcomputer/EnchantmentCracker#193]
![image](https://user-images.githubusercontent.com/69342345/89623952-1411ef80-d8c8-11ea-9778-497d2501f1a7.png)
I have installed the 64-bit Java and there's more tha 2GB RAM remains.but it can't find Java,and the solution of this is not in the tutorial.

**Comment by OneYellowLemon** [comment]
@rinwectebu You need to add java to your PATH, try following a tutorial like this one: https://javatutorial.net/set-java-home-windows-10

**Comment by rinwectebu** [comment]
@OneYellowLemon Thanks XD

**Comment by OneYellowLemon** [comment]
@rinwectebu Did it work?

**Comment by Earthcomputer** [comment]
?template stale
