### ISSUE TITLE
1.16.1 cannot crack player seed multiplayer

### ISSUE THREAD

**Issue by louisphilippe2** [Earthcomputer/EnchantmentCracker#196]
Hey EarthComputer,

I tried your program in single player 1.16.1 survival and it works. But then i jump into my fabric server and i won't be able to crack the player seed. I can crack the two seeds fine but then when i compute the player seed, i get an error. Is this even possible in multiplayer (single player for me, personal server)?

**Comment by Earthcomputer** [comment]
?template failed

**Comment by louisphilippe2** [comment]
OMG my dude you are the GOAT. I will give a try to what you sent me and give you an update. I'm just using a fabric server with a fabric client so there's no spigot or paper involved. I am however using mods like Phosphor and Lithium to optimize the server side so i'm wondering if that could have screwed with the RNG.

**Comment by Earthcomputer** [comment]
Phosphor and Lithium are amazing at preserving vanilla behaviour where possible, so it's not their fault ;)

**Comment by louisphilippe2** [comment]
[crash-2020-08-17_10.00.19-client.txt](https://github.com/Earthcomputer/EnchantmentCracker/files/5084686/crash-2020-08-17_10.00.19-client.txt)

I tried what you gave me and the game crashed in both single and multiplayer

**Comment by Earthcomputer** [comment]
Make sure you are using the correct Minecraft version

**Comment by louisphilippe2** [comment]
Ok nvm i had the wrong mod version. So i was able to crack the player seed in multiplayer. So it shows me the XP seed. How do i use that to say calculate the enchant xyz of a diamond pick axe now?

**Comment by Earthcomputer** [comment]
`/cenchant`

**Comment by louisphilippe2** [comment]
Yup got it to work :) This is cool!

**Comment by louisphilippe2** [comment]
I noticed i can't enchant with efficiency 5. Is there an issue or is it normal?

**Comment by louisphilippe2** [comment]
Wait Earth, in the program you have an option to enchant efficiency 5 but in the client mod, you can only go to 4. Is there a reason for this?

**Comment by Earthcomputer** [comment]
Some tool materials can enchant to efficiency 5 but not all.
