### ISSUE TITLE
[Unrelated] How's the pack.png seed finding going?

### ISSUE THREAD

**Issue by TheoCGaming** [Earthcomputer/EnchantmentCracker#197]
this is only for those participating in the pack.png stuff

**Comment by Earthcomputer** [comment]
This is not a chat room, join my discord for that

**Comment by TheoCGaming** [comment]
I can't I'M ONLY 12.

**Comment by Earthcomputer** [comment]
![image](https://user-images.githubusercontent.com/13084089/91070735-13e75300-e62f-11ea-8dd5-5378a8524c72.png)

**Comment by TheoCGaming** [comment]
h o l ' u p . . . Welp, guess I'm gone for the next 8 or so months

**Comment by ItzN00bPvP** [comment]
soon™
