### ISSUE TITLE
Helmet enchantments can't be predicted on helmets

### ISSUE THREAD

**Issue by NintendoBest** [Earthcomputer/EnchantmentCracker#2]
See video...

https://youtu.be/5AHXstTWUaM

So, like show in the video, i try to get Aqua_affinity & respiration and it tell me "impossible"
Even though it's right in my face in the game. (Btw i enchanted my next item and it worked correctly)

A did a double check and it seems like i can get respiration 3 by using a book though. I don't know what is wrong but yeah.

Have a nice day!

**Comment by Earthcomputer** [comment]
Confirmed, for aqua affinity and respiration on all types of helmet. Thanks for reporting!

Player seed (for reproducing): D00C78520464

**Comment by NintendoBest** [comment]
News: This issue also apply for Unbreaking with bows.

I have Unbreaking strait in my face on the enchant table and the cracker can't find it.

**Comment by Earthcomputer** [comment]
Fixed in version 1.0.2, which will be released later this weekend. #4 was unrelated.
