### ISSUE TITLE
Doc:  Level/Lapis requirement correction.

### ISSUE THREAD

**Issue by ehoffman2** [Earthcomputer/EnchantmentCracker#200]
Hello

I would like to know if the requirement is correct.

It says that you need:
- Lapis and levels for enchanting. 4 lapis+levels per enchanted item, plus 2 more lapis and 33 more levels.

Should it say 'and 29 more levels' instead?

For example, if you wish to enchant a single item, you need to have level 30 at the time you enchant.  Counting 2 levels/lapis to find the seed, and then 1 level/lapis before each enchant, then if you start with 33 levels/lapis (4 x 1 + 29), you're down to 31 after finding the seed, and down to 30 after the dummy.  30 is then enough to enchant.

Regards,
Eric

**Comment by Earthcomputer** [comment]
Yes, you are right, my video is correct, but the picture tutorial (which I didn't make) is wrong. I'll see if I can reach the person who made the picture tutorial to correct it.

**Comment by Hexicube** [comment]
Fixed, I worked out a minimum of 33 levels and 4 per _additional_ enchanted item and forgot to subtract 4 when I made the tutorial.

**Comment by Earthcomputer** [comment]
Oops :)

**Comment by ehoffman2** [comment]
I can not verify, the link seem to be broken in the Markdown file (probably need to be updated).

Regards,
Eric

**Comment by ehoffman2** [comment]
Sorry, my bad, the link is working fine.

Actually, it turns out that imgur made a move at the same time to force the new web layout, and that broke some browsers (including the one I'm using, Waterfox Classic, which is based on the older Firefox, which still support the 20+ legacy addons I can't live without and that there's no real alternative).  It work fine with the newer Firefox, or Chrome.  Issue is known in the Waterfox team.

Eric
