### ISSUE TITLE
The program most of the time fails while calculating the player seed

### ISSUE THREAD

**Issue by Blueil** [Earthcomputer/EnchantmentCracker#202]

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Blueil** [comment]
I did nothing wrong, but instead of doing the whole proccess, I just copy the 2nd seed to the 1st seed field and then just clearing the 2nd seed field and doing the step to get the xp seed, It's seems to work after I did that. Maybe there are more thing I can't do but they doesn't show in the list of disallowed action.

**Comment by Earthcomputer** [comment]
It sounds like you forgot to do the dummy enchantment at the start

**Comment by Earthcomputer** [comment]
?template stale
