### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by jr183** [Earthcomputer/EnchantmentCracker#206]
Hello! Here is a translation in French:

[EnchantmentCracker_fr.properties.txt](https://github.com/Earthcomputer/EnchantmentCracker/files/5288735/EnchantmentCracker_fr.properties.txt)

**Comment by Earthcomputer** [comment]
```
enchCalc.calculate.tooltip = <html>Appuyez pour calculer combien d'objets <i>vous devez</i> jeter pour obtenir ces enchantements</html>
```
This appears to be wrong. The italics are suppose to emphasize what you *would have* to drop *if you decide to pick those enchantments*, but you don't have to drop them otherwise. Could you adjust this translation to convey that?

The rest of it looks great, thanks!

**Comment by jr183** [comment]
Hi, you can replace with:
<html>Cliquez pour calculer combien d'objets <i>il vous faudrait</i> jeter pour obtenir ces enchantements</html>

**Comment by Earthcomputer** [comment]
I think we might be having the same problem as the Spanish translation in #199. Is there no way to capture the meaning of just the "would" being italic by re-wording the sentence in the French?

**Comment by jr183** [comment]
There is no word to express the conditional, in French it is according to the ending of the verb.

**Comment by Earthcomputer** [comment]
I know, but if you reword the entire sentence, is there a way for you to emphasize that you don't need to throw the items *now*, only if you *choose* the enchantment? Translations don't have to be word for word.

**Comment by jr183** [comment]
So the problem is the part in italics? This wording should be better:
``<html>Cliquez pour calculer le nombre d'objets qu'il vous faudrait jeter <i>si vous choisissez ces enchantements</i></html>``

**Comment by Earthcomputer** [comment]
Added, thanks for your contribution!
