### ISSUE TITLE
Enchcracker failed to launch even though I have all the requirements reached.

### ISSUE THREAD

**Issue by mahfy3w** [Earthcomputer/EnchantmentCracker#207]
I tried to launch enchcracker, but it says the following.
`Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .`

![image](https://user-images.githubusercontent.com/69918792/94372130-f01e9d80-0103-11eb-9db1-17273f2361ef.png)
![image](https://user-images.githubusercontent.com/69918792/94372136-02004080-0104-11eb-9dbc-abb4d1c1dd9e.png)
![image](https://user-images.githubusercontent.com/69918792/94372171-47247280-0104-11eb-8ddf-aa0700fe9d5c.png)

**Comment by Earthcomputer** [comment]
Your Java version doesn't say it's 64-bit, therefore it is 32-bit. Please install 64-bit Java.

**Comment by adororxllo** [comment]
![Screenshot (472)](https://user-images.githubusercontent.com/96339482/146641452-cb6dee9f-ec2d-4638-9b25-9cd37a88319f.png) I already have 64 - bit Java but it still keep saying (Error: Could not find or load main class enchcracker.EnchCrackerWindow
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is preferred for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 1GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have at least 1GB of RAM to spare.
4. Ensure that you have properly extracted enchcracker to a folder and are not running from the zip file.
5. Ensure that you extracted it into a normal directory, and not directly into the C drive or Program Files.
6. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .)

**Comment by wagyourtail** [comment]
This error is usually caused by only extracting the .bat file instead of the entire zip file. Please extract the whole zip file before running the .bat file: https://www.cedarville.edu/insights/computer-help/post/how-to-extract-files-from-a-zipped-compressed-folder
If that doesn't work, make sure you extract the file into somewhere where Java has permission to write to it (e.g. your desktop and not directly in your C drive)
