### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by The1Krispy** [Earthcomputer/EnchantmentCracker#208]
When I open it it opens console and claims that I have outdated Java.  But when I check Java it says I have fully updated.

**Comment by The1Krispy** [comment]
It says I need two gigs if ram which I have 10 sooooo.

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by The1Krispy** [comment]
Where do I install java to?

**Comment by Earthcomputer** [comment]
?template stale
