### ISSUE TITLE
Out of memory(macOS)

### ISSUE THREAD

**Issue by jsyangcs** [Earthcomputer/EnchantmentCracker#212]
At the start of step two when I set 15 shelfs and start the computation of second seed,  the program will go to "100%" but just fails. 
This kind of error has appeared 2 times. Any way to solve this?
jdk version: jdk1.8.0_251.jdk
macOs version: mojave 10.14.4
pc memory: 8GB

**Comment by jsyangcs** [comment]
I noticed in the shell script:
# Add default JVM options here. You can also use JAVA_OPTS and ENCHCRACKER_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xms2G" "-Xmx2G"'

should I edit this?
really like this program, hope to get help from you guys : )

**Comment by Earthcomputer** [comment]
#233 improved memory usage considerably. Try that
