### ISSUE TITLE
Saying I dont have enough ram

### ISSUE THREAD

**Issue by pexmate** [Earthcomputer/EnchantmentCracker#216]
I've tried running the program under multiple circumstances and keep running into this issue. I've also tried moving the install folder to different drives/folders etc. Could it maybe be due to me only having 8gb of ram total? Java is up to date and in 64bit
![ench cracker issue](https://user-images.githubusercontent.com/73496275/97217479-b8a41f00-179d-11eb-8757-d91deaa884e0.png)

**Comment by Earthcomputer** [comment]
Please paste the output of `java -version` here

**Comment by wlimpie** [comment]
I'm having the same issue
![Knipsel](https://user-images.githubusercontent.com/73801625/97818174-42258680-1ca1-11eb-8076-7ce694aa36c8.PNG)

**Comment by Earthcomputer** [comment]
@wlimpie you don't have 64-bit Java

**Comment by Earthcomputer** [comment]
?template 64bitjava
