### ISSUE TITLE
revised German language file 

### ISSUE THREAD

**Issue by GalaxyLinus** [Earthcomputer/EnchantmentCracker#217]
Hi,
I over-worked the file, now it is grammatically correct and smoother, e.g. some German Words are replaced with English ones, because everyone uses them and if you try to translate them, nobody knows what the meaning is. 
Greetings from Germany
Linus

PS: You may have to change the file type to .properties because GitHub does not let me upload the file with this extension.

[EnchantmentCracker_de.txt](https://github.com/Earthcomputer/EnchantmentCracker/files/5488587/EnchantmentCracker_de.txt)

**Comment by GalaxyLinus** [comment]
> Hi,
> I over-worked the file, now it is grammatically correct and smoother, e.g. some German Words are replaced with English ones, because everyone uses them and if you try to translate them, nobody knows what the meaning is.
> Greetings from Germany
> Linus
> 
> PS: You may have to change the file type to .properties because GitHub does not let me upload the file with this extension.
> 
> [EnchantmentCracker_de.txt](https://github.com/Earthcomputer/EnchantmentCracker/files/5488587/EnchantmentCracker_de.txt)

**Comment by Earthcomputer** [comment]
Hey, why was this closed?
