### ISSUE TITLE
Cannot open the cracker even though I have 2 gigs of ram and 64 bit java

### ISSUE THREAD

**Issue by hrebdik** [Earthcomputer/EnchantmentCracker#219]
I cannot open the cracker even though i have all them reqiuirements
![image](https://user-images.githubusercontent.com/74009817/98261573-e3079080-1f84-11eb-975d-397c4a379358.png)
![image](https://user-images.githubusercontent.com/74009817/98261593-e733ae00-1f84-11eb-89ec-868d57bf267d.png)
![image](https://user-images.githubusercontent.com/74009817/98261600-e7cc4480-1f84-11eb-859c-9f08cd93f4d7.png)
![image](https://user-images.githubusercontent.com/74009817/98261610-ea2e9e80-1f84-11eb-9060-0d6de7aa58ab.png)
![image](https://user-images.githubusercontent.com/74009817/98261763-177b4c80-1f85-11eb-8ace-2f44e138fdf3.png)

**Comment by Earthcomputer** [comment]
Can you please send the error message you get when you try to open the cracker?

**Comment by hrebdik** [comment]
![image](https://user-images.githubusercontent.com/74009817/98451871-59092480-214a-11eb-8848-240d4139e210.png)

**Comment by hrebdik** [comment]
I unzipped the jar inside of lib and this is what I found 
![image](https://user-images.githubusercontent.com/74009817/98452000-9326f600-214b-11eb-844e-40e3e3f6b50e.png)
![image](https://user-images.githubusercontent.com/74009817/98452001-9621e680-214b-11eb-90a2-d7ecf01a09dd.png)
![image](https://user-images.githubusercontent.com/74009817/98452002-97531380-214b-11eb-8a56-7b74aae153f5.png)
![image](https://user-images.githubusercontent.com/74009817/98452003-98844080-214b-11eb-82b1-2f8ab786b865.png)
![image](https://user-images.githubusercontent.com/74009817/98452005-99b56d80-214b-11eb-87ad-d2f718ab371f.png)
![image](https://user-images.githubusercontent.com/74009817/98452006-9ae69a80-214b-11eb-852a-78b5c94d52cc.png)
![image](https://user-images.githubusercontent.com/74009817/98452009-9d48f480-214b-11eb-931d-40cc0f839b80.png)

**Comment by Earthcomputer** [comment]
Make sure the zip you downloaded was extracted to a direction that Java has permission to load classes from. E.g. your desktop, not the root directory of your C: drive.

**Comment by hrebdik** [comment]
I think I have the things in a folder but that folder is in another folder which is on the desktop. Not sure already turned off the computer and im going to sleep.

**Comment by Earthcomputer** [comment]
Oh, and don't move the batch file

**Comment by hrebdik** [comment]
Decided to download v1.5 moved the zip from downloads to desktop unzipped it there and its still doesnt work even though its in a folder on desktop.

**Comment by Earthcomputer** [comment]
You weren't using 1.5? For fucks sake, *always* download the latest version of software.

**Comment by hrebdik** [comment]
I was

**Comment by Dirt-code** [comment]
i have the same issue here, how do i fix it?

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by Earthcomputer** [comment]
#237
