### ISSUE TITLE
[REQUEST] Detailed and updated explanation.

### ISSUE THREAD

**Issue by Hawkenist** [Earthcomputer/EnchantmentCracker#22]
Due to an issue, it was submitted even before I wrote, so here it is!

Although there is a tutorial on Youtube that explains the whole process of using the tool, it seems like it is outdated and I cannot find a reason why it's not working even though it was updated a week ago. 

The reason why I'm asking for a detailed updated explanation for the tool is because of some new features added to the tool and it might be causing issues that leads to me getting "No possible seeds" every time I try it.  

All helps would be appreciated!

**Comment by Hawkenist** [comment]
So, I somehow got both player seeds, maybe I left out some steps, but like before, I've been stuck with calculating the player seed. I'm not sure what to do with the force player seed so I left it blank and this happens:



Due to ISSUES, I cannot upload a screen shot but on the Player Seed page, when I calculate the two player seeds it results as Player seeds not found.

**Comment by asquared31415** [comment]
Ok, I'll work on that next.  Right now, I'm trying to fix one last minor UI issue with the dropdowns and then I plan to add the suggestion in issue 10.

**Comment by Earthcomputer** [comment]
Force player seed is for if you somehow already know the player seed, you can input it without cracking it. If you are cracking it (which you normally would be), you should leave the force player seed field blank.

**Comment by Hawkenist** [comment]
Ah. Okay, thank you. 
About the Wiki page, should I edit the Home page or add a new page as "Help"?

**Comment by Earthcomputer** [comment]
I'd say create a new page called "Tutorial" or something along those lines and link to it from the home page.

**Comment by Hawkenist** [comment]
I left a quick tutorial and some things that I believe I had to avoid for the tool to work, such as jumping. I'm not certain if jumping affects anything but I've included it in the not to do things.

**Comment by Earthcomputer** [comment]
Thanks so much for your contribution! I've added a few more things to the tutorial and also changed round a couple of things as well since there were a couple of steps you missed out. But overall it was a very good tutorial.

I think we can call this issue resolved now.
