### ISSUE TITLE
Unable to open the cracker

### ISSUE THREAD

**Issue by jotiesdev** [Earthcomputer/EnchantmentCracker#220]
Hey Earthcomputer,

So I tried to open the cracker and I received this error message:

'Error: Could not find or load main class enchcracker.EnchCrackerWindow
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues'

I'm pretty sure I installed Java and that Java is in my PATH.
I definitely have 64-bit Java and 2bg of RAM.
I'm not that good with Java and stuff so if you could please help me out that would be great.

Have a nice day,
- Joties

**Comment by Earthcomputer** [comment]
Please paste the output of `java -version` here

**Comment by jotiesdev** [comment]
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

**Comment by Earthcomputer** [comment]
Did you extract the cracker somewhere where Java has permission to load classes from? E.g. the Desktop and not directly in the C:\ drive.

**Comment by jotiesdev** [comment]
The zip file is on my desktop.

**Comment by Earthcomputer** [comment]
Ok but where did you extract it to?

**Comment by jotiesdev** [comment]
I didn't extract it.
I just opened it from the zip file

**Comment by Earthcomputer** [comment]
There's your issue

**Comment by jotiesdev** [comment]
I extracted it and it still gives the same error.

**Comment by Earthcomputer** [comment]
1) Are you actually running the extracted file?
2) Did you extract it to somewhere Java has permission e.g. desktop?
3) Did you *not* move the batch file after extracting it?
4) Please send a screenshot of the error.

**Comment by jotiesdev** [comment]
1. yes
2. I extracted it to the desktop
3. yes
4 
![beepboop](https://user-images.githubusercontent.com/70667260/98449673-31826f80-20ea-11eb-9bc0-8dc6d16a1192.jpg)

**Comment by Earthcomputer** [comment]
That is not the same error. Please make sure you actually have enough memory available on your system by closing other program you're not using.

**Comment by jotiesdev** [comment]
I closed everything except the file explorer. 
If I view my RAM info it says I have 3.89 GB useable.
