### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ARandom90YearOld** [Earthcomputer/EnchantmentCracker#221]
I have enough storage but this message comes up:
Error occurred during initialization of VM
**Could not reserve enough space for 2097152KB object heap** - I have 34000000kg of storage
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
Press any key to continue . . .

**Comment by Earthcomputer** [comment]
?template 64bitjava

**Comment by ARandom90YearOld** [comment]
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

**Comment by ARandom90YearOld** [comment]
This is a picture 
![image](https://user-images.githubusercontent.com/74135722/98463664-b043df00-21b4-11eb-887c-00e286484ace.png)

**Comment by Earthcomputer** [comment]
That is a picture of the installer you either haven't run or set the PATH to properly. Please read what the bot says.
