### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by idk300** [Earthcomputer/EnchantmentCracker#225]
when i try to open the batch file it says that JAVA_HOME is set to an invalid directory. I am running java 64 bit, and also i don't really know about coding and stuff.
![image](https://user-images.githubusercontent.com/74947576/100049798-2cd5ef00-2e3e-11eb-8752-b839ad2f87ec.png)

**Comment by idk300** [comment]
i forgot to download the java devloper kit

**Comment by idk300** [comment]
I am reopening this issue becoz when installed java and tried it didn't work I am getting the same issue and even reinstalled everything related to the enchantment cracker and I also download the latest version

**Comment by SaumitraVerma** [comment]
Seems like a problem with java installation.
try running `java -version` in command prompt

**Comment by idk300** [comment]
Ok

**Comment by idk300** [comment]
What to do now
![image](https://user-images.githubusercontent.com/74947576/100179414-024a6b80-2efc-11eb-8f31-0faabc4e4bb3.png)

**Comment by idk300** [comment]
![image](https://user-images.githubusercontent.com/74947576/100179491-2c039280-2efc-11eb-99bb-ccc6e5493f0d.png)

**Comment by Earthcomputer** [comment]
JAVA_HOME is set to a JDK you appear to have uninstalled. Set JAVA_HOME to one of those ones you have installed. [Here](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) is how to set environment variables on Windows.

**Comment by idk300** [comment]
Ok

**Comment by idk300** [comment]
yes it is now working thank you 
![image](https://user-images.githubusercontent.com/74947576/100237177-90524080-2f54-11eb-899f-e3bd7c2221a3.png)
