### ISSUE TITLE
Saying I don't have enough storage

### ISSUE THREAD

**Issue by Kiwis741** [Earthcomputer/EnchantmentCracker#229]
So it keeps saying I don't have enough storage but I do.
![image](https://user-images.githubusercontent.com/75755969/101682377-64d15a80-3a18-11eb-9f9a-fda2304227e0.png)
![image](https://user-images.githubusercontent.com/75755969/101682411-7286e000-3a18-11eb-956e-e37c1f89acfc.png)

It says I don't have 64-bit
![image](https://user-images.githubusercontent.com/75755969/101682497-8cc0be00-3a18-11eb-822c-ca7aabe742bc.png)

So I've done this 
![image](https://user-images.githubusercontent.com/75755969/101682656-c5609780-3a18-11eb-8332-6a9d9a264558.png)
as well as add the Home to the path but I'm not sure what to do if my Java is this though
![image](https://user-images.githubusercontent.com/75755969/101682866-0eb0e700-3a19-11eb-8c03-63d8b4ab76b2.png)

**Comment by Kiwis741** [comment]
I have used the link from previous issues to download java 
https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239858_230deb18db3e4014bb8e3e8324f81b43

**Comment by Earthcomputer** [comment]
Try rebooting

**Comment by Kiwis741** [comment]
I have, I think I did something wrong with the environmental variables, I just don't know what

**Comment by Kiwis741** [comment]
![image](https://user-images.githubusercontent.com/75755969/101747978-cf1de580-3a80-11eb-947d-e9f4d32fa7b3.png)
still doesn't seem like its 64-bit

**Comment by Earthcomputer** [comment]
Are you sure that the folder `%ProgramFiles%\Java\jre1.8.0_221\bin` exists?

**Comment by Kiwis741** [comment]
This is all in my Java folder right now 
![image](https://user-images.githubusercontent.com/75755969/101801352-11681680-3ac3-11eb-98a0-ee8207104444.png)

**Comment by Earthcomputer** [comment]
#237
