### ISSUE TITLE
Feature request: beieng able to choose multiple enchantments at once

### ISSUE THREAD

**Issue by yolomilk** [Earthcomputer/EnchantmentCracker#23]
I would appreciate to add more enchantments at once in the Manipulate tap.  They would have to be separated by commas, semicolons or something else.
The Idee is that you can easily just paste a String like: "unbreaking, respiration, aqua_affinity ,protection" in the Enchantment field instead of having to press for each enchantment the button and typing it into the Field.
It could be nice to have all the Strings for the best enchantments for armor and tools in a Textfile or so.

**Comment by Earthcomputer** [comment]
Relates to #24

**Comment by Earthcomputer** [comment]
With the new UI changes I think most of what this was asking for is obsolete, and the rest of it superseded by #24, so I'm going to close it now.
