### ISSUE TITLE
Excuse me, what is the problem, there is no response after pressing any key 

### ISSUE THREAD

**Issue by CMZ-GuaYan** [Earthcomputer/EnchantmentCracker#254]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is preferred for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 1GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have at least 1GB of RAM to spare.
4. Ensure that you have properly extracted enchcracker to a folder and are not running from the zip file.
5. Ensure that you extracted it into a normal directory, and not directly into the C drive or Program Files.
6. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
请按任意键继续. . .

**Comment by Earthcomputer** [comment]
Issue reports in English, please. Here is your problem:

> ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

**Comment by CMZ-GuaYan** [comment]
Google Translate: Because I am in China and cannot see your graphic tutorials, please teach me how to set JAVA_HOME

**Comment by BenCat07** [comment]
you did not install java

**Comment by CMZ-GuaYan** [comment]
Google Translate: Installed, otherwise how can I play Minecraft, so is my installed JAVA not detected?

**Comment by Earthcomputer** [comment]
Minecraft comes with its own Java installation, and it uses that. Nothing else on your computer uses that Java installation.

**Comment by CMZ-GuaYan** [comment]
Google Translate: Sorry, I don’t understand this translation, it means I need to reinstall JAVA? But I have reinstalled it and it is still useless

**Comment by CMZ-GuaYan** [comment]
Google Translate: Sorry, it has been solved. I found a solution posted by others on the Internet, just add the Path in the environment variable. thank you
