### ISSUE TITLE
Initial heap size set to a larger value than the maximum heap size

### ISSUE THREAD

**Issue by liuwx233** [Earthcomputer/EnchantmentCracker#267]
Picked up _JAVA_OPTIONS: -Xmx512M
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size

I have spared enough RAM for this program, How to solve it plz...

**Comment by Earthcomputer** [comment]
> Picked up _JAVA_OPTIONS: -Xmx512M

What?

**Comment by liuwx233** [comment]
When I double_click the bat file, it shows:
"
Picked up _JAVA_OPTIONS: -Xmx512M
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Failed to launch enchcracker!
....
"
I opened it in a pure ascii path and in D:\\..

**Comment by Earthcomputer** [comment]
_JAVA_OPTIONS isn't part of enchcracker. That's your end.
