### ISSUE TITLE
Minecraft 1.17.1 not giving the correct enchants

### ISSUE THREAD

**Issue by E0hp1** [Earthcomputer/EnchantmentCracker#272]
When I do this in Minecraft 1.17.1 (Singleplayer) it does not give me the correct enchants. I am not using any mods so I don't know what is making it not work.

**Comment by TriRetr0** [comment]
Same

**Comment by ImUrX** [comment]
If you run, have potion effects, eat, get an XP orb (new) you will change your RNG

**Comment by E0hp1** [comment]
I did not do any of those I just was on the Enchanting table.

**Comment by ImUrX** [comment]
i tried it multiple times in 1.17.1 and it works xD

try following carefully the [guide](https://imgur.com/a/oaxCC5x) and maybe take a photo of your setup

**Comment by E0hp1** [comment]
Ok I will try

**Comment by E0hp1** [comment]
Thx it works now
