### ISSUE TITLE
Can't find 'bin' folder

### ISSUE THREAD

**Issue by FishusChrist** [Earthcomputer/EnchantmentCracker#287]
I am not a coder at all but when i downloaded and unpacked the file i was unable to find the bin file to open the program, where can I find it?

**Comment by RGFTheCoder** [comment]
make sure you download the zip file at https://github.com/Earthcomputer/EnchantmentCracker/releases/latest (Not the sources ones). If you want to build from source, its more complex, but is explained in the readme

**Comment by FishusChrist** [comment]
yep, that fixed it, thank you.
