### ISSUE TITLE
cant do 1.17

### ISSUE THREAD

**Issue by meastromees** [Earthcomputer/EnchantmentCracker#288]
i instalded the 1.8 to 1.17 version but i can only do 1.16.5 . i did instalded it multyble times but that dint help. 
mabey it is beycouse of an ather problem this one: https://github.com/Earthcomputer/EnchantmentCracker/issues/274
[sorry i am not inglish so cant realy writhe good]

**Comment by wagyourtail** [comment]
duplicate, #276 #277 #278 #279 #282, please search for existing issues before creating a new one
