### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by BraveCaperCat** [Earthcomputer/EnchantmentCracker#321]
How do i download the .jar mod?

**Comment by xpple** [comment]
This is not a mod, this is a standalone Java application. If you want to use the Minecraft mod, go to [clientcommands's releases](https://github.com/Earthcomputer/clientcommands/releases).

**Comment by BraveCaperCat** [comment]
Now, i'm asking that issues page how to install the .jar

**Comment by BraveCaperCat** [comment]
And FAST Response time

**Comment by xpple** [comment]
> Now, i'm asking that repository how to install the .jar

First go to [clientcommands's releases](https://github.com/Earthcomputer/clientcommands/releases), then click on `clientcommands-2.6.4.jar` to download the file. Lastly move the file to your `.minecraft/mods` folder and launch Minecraft with the Fabric Loader.
