### ISSUE TITLE
If the XP-Seed Starts with a zero it gets  copied incorrectly

### ISSUE THREAD

**Issue by IPerrrY** [Earthcomputer/EnchantmentCracker#33]
![screenshot_5](https://user-images.githubusercontent.com/42246945/43910823-27e6d68c-9bfe-11e8-82c7-9ae7332c7ef0.png)
![screenshot_6](https://user-images.githubusercontent.com/42246945/43910824-2809d57e-9bfe-11e8-937c-29b8420f64c5.png)

**Comment by Earthcomputer** [comment]
What do you mean by "copied"?

**Comment by Earthcomputer** [comment]
Oh I see, and I see what's causing it. Minor issue I guess, it should be interpreted the same way with or without the leading 0. But a bug nonetheless.
