### ISSUE TITLE
EnchCracker on curseforge?

### ISSUE THREAD

**Issue by TheOneThatWanderedIn** [Earthcomputer/EnchantmentCracker#338]
Hi

I was just wondering if you intended to post the mod on curseforge. if not, would you be agreeable to someone else doing so? I ask solely because of convenience -- with curseforge's new app, it becomes so much easier to load mods as long as they're on curseforge.

**Comment by Gaming32** [comment]
I would highly recommend trying out [Modrinth](https://modrinth.com/mod/client-commands).

**Comment by Earthcomputer** [comment]
It's not a mod.
