### ISSUE TITLE
什么时候支持1.19？

### ISSUE THREAD

**Issue by li1243893836** [Earthcomputer/EnchantmentCracker#345]
现在玩最新的版本，附魔太难了，大佬什么时候更新1.19啊

**Comment by Earthcomputer** [comment]
Issues in English only please. 1.19 is already supported.

**Comment by SKYchiEz** [comment]
> 现在玩最新的版本，附魔太难了，大佬什么时候更新1.19啊



> Issues in English only please. 1.19 is already supported.

Can you make the enchantcracker in 1.19 but not a mod? I have many mods in forge and can't install farbic. maybe more people will meet the problem
