### ISSUE TITLE
Can it use on mod?

### ISSUE THREAD

**Issue by PokeMC-Potter** [Earthcomputer/EnchantmentCracker#348]

**Comment by erxson** [comment]
clientcommands /ccrackrng + /cenchant

**Comment by erxson** [comment]
![image](https://user-images.githubusercontent.com/50082485/210320545-fce3af4b-7b7b-421d-b49f-0000693a5f99.png)

**Comment by erxson** [comment]
@PokeMC-Potter close the issue?
