### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aserted** [Earthcomputer/EnchantmentCracker#359]
idk why but its not working, can someone please help.

**Comment by aserted** [comment]
well i got the issue how do i set up set the JAVA_HOME variable

**Comment by Lagesan** [comment]
Me either
![image](https://github.com/user-attachments/assets/a175016c-562f-491c-b456-954b6e1da853)

**Comment by Earthcomputer** [comment]
Install Java properly.

**Comment by Lagesan** [comment]
Thanks.It works now
