### ISSUE TITLE
Fix for OSX native library loading error

### ISSUE THREAD

**Issue by NWindy5** [Earthcomputer/EnchantmentCracker#36]
[enchcracker.zip](https://github.com/Earthcomputer/EnchantmentCracker/files/2454737/enchcracker.zip)

Solved by recompile the shared library.
Just execute enchcracker_OSX.sh instead of enchcracker.sh
IDK where should I post it so I post it here.

p.s. You need to name the library file to *.jnilib instead of *.so on OSX.

**Comment by Antonight1** [comment]
jni.h file not found
i've installed jdk latest version, xcode comand line tools also but when i run the osx file it can't find the jni.h file

**Comment by mitchjmac** [comment]
> jni.h file not found
> i've installed jdk latest version, xcode comand line tools also but when i run the osx file it can't find the jni.h file

I was getting that error too. 
### First make sure $JAVA_HOME is set:
```bash
echo $JAVA_HOME
```
It should look something like:
```bash
/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home
```
If it does, great skip down to the next section. If it's blank, instead:
```bash
sudo find / -name javac #this will ask for your password
# wait for the path that looks like mine then, <control>c
nano ~/.bash_profile
```
Type in:
```bash
export JAVA_HOME="the_path_you_found_above"
```
Then hit \<control\>x to exit and then y to save the changes
Finally
```bash
source ~/.bash_profile
```

### Change the c++ complier
Change "clang" to "g++" in enchracker_OSX.sh and then it should work. You'll get an warning about incompatible string types but ignore it. Enter "y" to both the "override" prompts and it should work.

**Comment by Antonight1** [comment]
hey man, can you help me a little?
I don't really know how to do it on my own, I don't know if I'm doing it right.

**Comment by mitchjmac** [comment]
@Antonight1 What part are you stuck on?

**Comment by Earthcomputer** [comment]
Thanks! Added to the new release.
