### ISSUE TITLE
I have installed java. But not working

### ISSUE THREAD

**Issue by cup-of-yogurt** [Earthcomputer/EnchantmentCracker#361]
I have installed java and set the java path. Still have more than 10G RAM. Please take a check, thanks. The error message is as follows:
![1](https://github.com/Earthcomputer/EnchantmentCracker/assets/151763393/43eecf10-31a0-4870-b6c6-faec8fbf3ddf)
![image](https://github.com/Earthcomputer/EnchantmentCracker/assets/151763393/8b2289f0-9e60-4f1f-9dc6-7d55e34a614d)
![image](https://github.com/Earthcomputer/EnchantmentCracker/assets/151763393/2874f3d7-e66f-4d6d-b418-f1cf56562037)

**Comment by gukuai** [comment]
Bro try newer java,andI have solved this problem by using the newer java (jdk19)
