### ISSUE TITLE
No player seed found with found 2 xp seeds

### ISSUE THREAD

**Issue by PankajKumar000** [Earthcomputer/EnchantmentCracker#364]
I am using the Terminal / app / zip file version to crack my enchantments (not mod version)

Minecraft : 1.20.4 fabric-vanilna-survival
zip file : 1.6
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/14895482/enchcracker.log)

I am following all the steps correctly given by EARTHCOMPUTER and i don't know how much time i performed those steps
getting xp seed has no problems but when i click on the button CHECK it says FAIL , the log out output says  "No player seed found" 
i am performing this in minecraft version "1.20.4" , is my minecraft version causing all the problems or somthing else?
am I doing steps in wrong way? Please help me to fix this!

**Comment by Earthcomputer** [comment]
You must have done something wrong. It works for everyone else. If you want you can join the discord and ask for support in the support channel. I recommend in this case to provide a short video of what you're doing because otherwise it's impossible to tell what you've done wrong.
