### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Its-Stone** [Earthcomputer/EnchantmentCracker#366]
How do I use the in-game mod? No new menus are visible, nor available control settings etc. Do I have to be on multiplayer for it to work?

**Comment by Earthcomputer** [comment]
This is not the repository for the in-game mod.

**Comment by Its-Stone** [comment]
Then where do I make tickets regarding this? In the readme section it said to make it here so I did

**Comment by Earthcomputer** [comment]
That is for the external tool, not the in-game mod.
