### ISSUE TITLE
Bow enchantements error prediction

### ISSUE THREAD

**Issue by NintendoBest** [Earthcomputer/EnchantmentCracker#4]
See video... (I first enchanted a diamond sword and double check to see if everything is ok)
Start to utile i; enchant my bow is speed up by: +75%

https://youtu.be/VqT8Qic05-U

So, when i was trying to see if i can get unbreaking, the enchant couldn't be found.
When i enchanted the bow with the above following in the video, Infinity get swapped with unbreaking instead.
I did the test 3 time, and it always went back with:
Power 4
Flame
Punch 2
Unbreaking 3 (instead of infinity)

Ｙｅｓ， ｔｏｔａｌｌｙ ｍｉｓｓｅｄ ｔｏ ｒｅｍｏｖｅ ｔｈｅ ｔｏｒｃｈ ｂｅｆｏｒｅ ｅｎｃｈａｎｔｉｎｇ ｔｈｅ ｓｗｏｒｄ． Ｌｏｌ

**Comment by Earthcomputer** [comment]
Looking closely at the video it appears to say that unbreaking 3 is impossible to get on a bow, which I imagine is the real problem. It's also probably a similar problem to #2, which I will investigate now.

**Comment by Earthcomputer** [comment]
It didn't happen to me when I tested it. If it happens to you again, can you also give me the player seed to help me reproduce it?

**Comment by NintendoBest** [comment]
Sure! Gonna try that now.

**Comment by Earthcomputer** [comment]
Thanks for the video, they're very helpful! I was able to reproduce all those enchantments and will get to fixing it now.

**Comment by Earthcomputer** [comment]
Fixed. I forgot to allow unbreaking on bows.

**Comment by NintendoBest** [comment]
Np! I'm not just doing that for it to get fixed anyways, but also to have a 100% false-less enchanting program :P
