### ISSUE TITLE
Remove third Enchantment Level Field

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/EnchantmentCracker#40]
The third field always has the Level: Used Bookshelves[max15]*2; meaning:
Its 30 @15 
28@14
26@13
etc...
We could save a bit of time if we didnt have to put in the last enchantment slot, and its useless anyway ^^

**Comment by Earthcomputer** [comment]
Although correct for higher levels, the last field does give information for fewer number of bookshelves. So I'm closing this as not an issue.
