### ISSUE TITLE
Library load error Windows 10 64bit

### ISSUE THREAD

**Issue by C0d0Type23** [Earthcomputer/EnchantmentCracker#41]
When I start echcracker on my windows 10 64 bit its get me an error and enchcracker is slow and almost crash every 5 sec
![capture](https://user-images.githubusercontent.com/36166761/50577282-101c1280-0df3-11e9-8fac-aac46b4a6588.PNG)
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/2719710/enchcracker.log)

**Comment by Earthcomputer** [comment]
Did you mess with the native library path?

**Comment by C0d0Type23** [comment]
No, I just add the enchcracker.zip and the EnchantmentCracker-1.2.1.zip (Source Code) into the main directory but nothing else

**Comment by Earthcomputer** [comment]
Okay, you don't need the source code, just the enchcracker.zip. But that doesn't explain the issue.
I googled the error "The specified procedure could not be found" and it seems to happen when Java is looking in the wrong place for native libraries. How are you running it? Using the batch file?

**Comment by C0d0Type23** [comment]
yep

**Comment by Earthcomputer** [comment]
Okay, I'll investigate, thanks for reporting!

**Comment by C0d0Type23** [comment]
No problem!

**Comment by Earthcomputer** [comment]
What happens if you add:
```
-Djava.library.path=.
```
to the batch file after the `javaw` word?

**Comment by C0d0Type23** [comment]
Same issue

**Comment by C0d0Type23** [comment]
I also tried to put the whole path of the directory and not the dot and same issue

**Comment by C0d0Type23** [comment]
![capture2](https://user-images.githubusercontent.com/36166761/50577708-fdf2a200-0dfb-11e9-827a-6871e1bae3fe.PNG)

**Comment by KaptainWutax** [comment]
the log please :D

**Comment by C0d0Type23** [comment]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/2719737/enchcracker.log)

**Comment by C0d0Type23** [comment]
Sorry its was the wrong log
this is the one
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/2719738/enchcracker.log)

**Comment by KaptainWutax** [comment]
> -Djava.library.path=</Users/William/Desktop/enchcracker>
All I can think of right now.

**Comment by C0d0Type23** [comment]
Not working better and same error

**Comment by Earthcomputer** [comment]
Should be fixed now with the removal of the native library
