### ISSUE TITLE
"Unexpected Error occured"

### ISSUE THREAD

**Issue by deadjak** [Earthcomputer/EnchantmentCracker#42]
tried launching the program via the .bat and this happened

![image](https://user-images.githubusercontent.com/27832787/51638703-b35cd500-1f24-11e9-8e57-3ae4ab8183ec.png)
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/2789258/enchcracker.log)

**Comment by Earthcomputer** [comment]
I'm gonna be honest, I don't know what the heck is causing this.
So I'm gonna resort to my usual advice, try allocating more memory?

**Comment by Earthcomputer** [comment]
Did you ever resolve this issue?

**Comment by Earthcomputer** [comment]
If this is still an issue, reply and I can reopen.
