### ISSUE TITLE
EnchantmentCracker not working

### ISSUE THREAD

**Issue by ElementalSamurai** [Earthcomputer/EnchantmentCracker#44]
For some reason it isn't working, it says I can run it on a 32-bit one, but then it says

java.lang,OutOfMemoryError: Java Heap Space

**Comment by Earthcomputer** [comment]
Try allocating more memory.

**Comment by Earthcomputer** [comment]
Given no response, I'm going to close this issue for now. If you are still having problems, reply and I can reopen.
