### ISSUE TITLE
Unable to add riptide 3

### ISSUE THREAD

**Issue by MrCrackerplays** [Earthcomputer/EnchantmentCracker#47]
when using trident as item it's not possible to add riptide 3 (1 and 2 do work)

but then when I chose to use riptide 2 and went through the steps ingame it turned out to be riptide 3 anyways
![Capture2](https://user-images.githubusercontent.com/30552654/55199097-13882580-51b9-11e9-9097-3c2e8b75bb39.PNG)

**Comment by Earthcomputer** [comment]
What Minecraft version?

**Comment by MrCrackerplays** [comment]
1.13.2

**Comment by KaptainWutax** [comment]
Looks like Riptide 2 is already in the list...

**Comment by MrCrackerplays** [comment]
even when it wasn't on the wanted list I couldn't add it

**Comment by Earthcomputer** [comment]
Fixed in version 1.4.1
