### ISSUE TITLE
cracker not working

### ISSUE THREAD

**Issue by realkevinS** [Earthcomputer/EnchantmentCracker#48]
the .bat file never seems to never open, i tried to open the .jar and it gives me the java heap space error

**Comment by Earthcomputer** [comment]
Allocate more RAM. The cracker needs about 3 gigs iirc.

**Comment by realkevinS** [comment]
stupid question, but how do i do that?

**Comment by Earthcomputer** [comment]
In the bat file it has the memory set I believe (`-Xmx2g` or something. 2g means 2GB). Try increasing it.

**Comment by realkevinS** [comment]
3 gigs does nothing, so i made it 4 and this is what i get http://prntscr.com/n71rgd
