### ISSUE TITLE
Can't use more than 15 bookshelfs.

### ISSUE THREAD

**Issue by GlitchHead** [Earthcomputer/EnchantmentCracker#5]
When I try and use the program there is 1 bookshelf left with some possible seeds and I can't use 1 bookshelf in the program as there are missing slots. I have spent a unhealthy amount of time trying to see what I'm doing wrong and I'm really confused. Please allow us to use 16 bookshelfs or more.

**Comment by GlitchHead** [comment]
Nevermind. I found out what I was doing wrong. I never thought of adding bookshelfs back lol.

**Comment by Earthcomputer** [comment]
15 bookshelves is the max anyway...
