### ISSUE TITLE
enchcracker not launching

### ISSUE THREAD

**Issue by Greenthumbs** [Earthcomputer/EnchantmentCracker#50]
When I open the enchcracker.bat file all that happens is that it opens the console then immediately closes, which I assume should happen, but then after that nothing happens.

Log file: [enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3046068/enchcracker.log)

**Comment by hube12** [comment]
you are on a 32 bit system, earth go add enchantcracker32.dll

**Comment by Greenthumbs** [comment]
Thank you for the quick response. My system is 64 bit, however, where would I find enchcracker32.dll. I have searched github and could not find.

**Comment by hube12** [comment]
i mean your java environnement is detected as 32 bit, you might want to download the 64 bit java jre https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.exe and use it to launch the .jar in the archive

**Comment by Greenthumbs** [comment]
Thank you for your help, all seems to work as it should and I can't wait to use it.
