### ISSUE TITLE
Can't add level 5 enchantments

### ISSUE THREAD

**Issue by Connor124** [Earthcomputer/EnchantmentCracker#51]
If I was trying to enchant a ```diamond_sword``` with ```sharpness 5``` I get a red border around the box. If I just put in ```sharpness``` it adds ```sharpness 4``` to the list. 

This also happens for efficiency and other level five enchants.

**Comment by KaptainWutax** [comment]
You can't enchant sharpness 5...

**Comment by Connor124** [comment]
In Enchantments.java at line 208 none of the level 5 enchants work.

Sorry, can't link because I'm on mobile.

**Comment by Earthcomputer** [comment]
You can't get sharpness 5 or efficiency 5 in an enchanting table. Off the top of my head, I think smite 5 is the only one you can get straight out of an enchanting table.
For enchanting tables, you can't straight up read the max level of the enchantment and expect to be able to get it. Instead, you have to maximize the random values in the enchantment table algorithm, as such: https://github.com/Earthcomputer/EnchantmentCracker/blob/master/java/src/enchcracker/Enchantments.java#L483
