### ISSUE TITLE
Enchantment cracker doesn't work on papermc?

### ISSUE THREAD

**Issue by dankman2** [Earthcomputer/EnchantmentCracker#53]
I tested various times of getting xpseed but it say player seed not found but I switched the server software to spigot and it worked for me?

**Comment by Earthcomputer** [comment]
That is probably true, and if that's the case there's nothing I can do about it, sorry.

**Comment by slmrojo** [comment]
oh the server i'm trying this on is paper too. Would be nice to put this in the readme or something
