### ISSUE TITLE
How to Update?

### ISSUE THREAD

**Issue by PKMWM1** [Earthcomputer/EnchantmentCracker#55]
How do you update or compile the latest version? What programs and files do you need? I downloaded the latest commit and I can't figure it out and I really want to use it for 1.14. Any help would be appreciated.

**Comment by BlueDolphinCow** [comment]
https://github.com/Earthcomputer/EnchantmentCracker/releases
the latest version is 1.13.2
https://github.com/Earthcomputer/EnchantmentCracker/wiki

**Comment by leumasme** [comment]
@Earthcomputer Will a 1.14 version come? Is it even needed, did anything change?

**Comment by Coppertine** [comment]
However, there has been a commit to update to 1.14 (with the addition of the previous incompatable items). Is there a way to import the project in and compile?

**Comment by leumasme** [comment]
@Coppertine look at #61 that was referenced, 
> That commit was supposed to make it work for 1.14, but it doesn't for some reason, that still needs to be looked into.

**Comment by Pascaloli** [comment]
Hey, its been almost a month this issue is open now, is there any update so far?

**Comment by Earthcomputer** [comment]
My exams just recently finished, this was a bit of a harder update than usual. The update is out now :)
