### ISSUE TITLE
enchcracker.bat not detecting any enchcracker.jar to launch in Temp Folder

### ISSUE THREAD

**Issue by forshale** [Earthcomputer/EnchantmentCracker#59]
http://prntscr.com/nql0kw

after awhile of experimenting, i noticed that the folder for the .bat file would be created in Temp slightly AFTER enchcracker.bat gives me the error message.

I also can't run enchcracker.jar without it crashing around 27 mil seeds or something, Im thinking adding more ram to the jar file would work, but unsure how to do that

I've already tried adding more RAM to the enchcracker.bat file.

**Comment by Earthcomputer** [comment]
Can you try extracting the zip to a folder other than the temp folder? Say, your desktop for now, and see if it works then?

**Comment by forshale** [comment]
That worked, Weird how that works thanks 👍

**Comment by Earthcomputer** [comment]
Must be a file permission issue ;)
