### ISSUE TITLE
Confused overall

### ISSUE THREAD

**Issue by Fabiososo** [Earthcomputer/EnchantmentCracker#60]
Hey guys, I'm kinda lost here. I've downloaded the enchcracker.zip file, extracted the folder, but when I click README it tells me to open enchcracker.bat, which was never in the folder in the first place. I've instead decided to open the executable Jar File called enchcracker to only be met with "Can't load AMD 64-bit.dll on a IA 32-bit platform", but I have a 64 bit operating system as well as 64-bit Java. It also says to include the contents of the log file (enchcracker.log) which also isn't in the folder. Another line says "Press OK to continue with a slower Java implementation of the XP seed finder." I click okay to be met with "An unexpected error occured! /n java.lang.OutOfMemoryError: Java heap space" Can I please get help with this, as I don't know what I'm doing wrong

**Comment by Platypus3112** [comment]
The issue here is the lack of a description.

**Comment by Fabiososo** [comment]
> 
> 
> The issue here is the lack of a description.

Sorry, I accidentally published the title and decided to edit in the description

**Comment by Earthcomputer** [comment]
Hi, where did you download the zip from? Did you use the button called "Clone or Download" or did you go to the releases page? "Clone or Download" is for downloading the source code and is not the one you want in most cases.

**Comment by Fabiososo** [comment]
Hi, I had downloaded it from the releases page, the one with enchcracker.zip, Source code (zip) and Source code (tar.gz)

**Comment by Earthcomputer** [comment]
You say enchcracker.bat was never in the folder. Can you show me what is in the folder?

**Comment by Earthcomputer** [comment]
Closing since no response in a while. If you still have this issue, just reply and I can reopen it.
