### ISSUE TITLE
problem with loading?

### ISSUE THREAD

**Issue by Leikonka** [Earthcomputer/EnchantmentCracker#62]
first, sorry for my english, its very imperfect, im running on WIN10 64 bit 64bit java and NVIDIA graphic

issue: i started the enchcracker.bat and cmd window was there on half sec, then disapeared and nothink happend, so then i started enchcracker.jar and happend this:

![error 1 enchcracker](https://user-images.githubusercontent.com/51082150/58417065-f3bf9180-8083-11e9-9193-56e6086b033a.png)

after i click OK this shows:
![error enchcracker 2](https://user-images.githubusercontent.com/51082150/58417195-4ef18400-8084-11e9-9f14-a26689559a65.png)

im pretty unskilled, so can you please write solution (if is some there) by step by step?
Thanks

**Comment by MCRcortex** [comment]
can you please upload enchcracker.log

**Comment by MCRcortex** [comment]
can you please upload enchcracker.log

**Comment by Leikonka** [comment]
Yes, sorry

[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3223632/enchcracker.log)

**Comment by MCRcortex** [comment]
ok so you need to give more ram to java. thats your issue

**Comment by Leikonka** [comment]
you mean rewrite in enchcracker.bat this: 
@echo off
start javaw -Xmx2g -jar "%~dp0\enchcracker.jar"
 on FE this? : 
@echo off
start javaw -Xmx4g -jar "%~dp0\enchcracker.jar"

**Comment by MCRcortex** [comment]
yea, try and see

**Comment by Leikonka** [comment]
thsi happend
![eroor 3](https://user-images.githubusercontent.com/51082150/58418934-87479100-8089-11e9-8049-26cc94aeecf3.png)

**Comment by MCRcortex** [comment]
how much ram do you have in your computer?

**Comment by Leikonka** [comment]
8

**Comment by Earthcomputer** [comment]
You have 32-bit Java, you need 64-bit Java. Please follow the instructions on the dialog and install 64-bit Java.
