### ISSUE TITLE
Player Seed not Found on Mac

### ISSUE THREAD

**Issue by goncaloRM** [Earthcomputer/EnchantmentCracker#64]
I have downloaded the enchcracker.zip file from the internet on my mac and opened the ehnchcracker.jar file right away. I get the error message "Failed to load native enchcracker library!", with a very big message following. I then press OK, and I am able to use the XP Seed Finder. I have found both XP Seeds, but when I try to calculate the player seed, it has not worked. This was all tested on a creative single player server.

**Comment by Earthcomputer** [comment]
Did you run enchcracker_OSX.sh. like it said in the readme?

**Comment by goncaloRM** [comment]
How do I run it? I double click the file and all I get is a text edit file saying:

#!/bin/bash
echo "Please make sure you have Xcode command line tools and jdk installed on your Mac."
mkdir tmp
pushd tmp
git clone https://github.com/Earthcomputer/EnchantmentCracker
pushd EnchantmentCracker/native/src
clang -I $JAVA_HOME/include -I $JAVA_HOME/include/darwin -shared -std=c++11 -o libenchcracker.jnilib enchcracker.cpp
popd
popd
rm libenchcracker.so
cp ./tmp/EnchantmentCracker/native/src/libenchcracker.jnilib .
rm -r ./tmp
java -Xmx2g -Djava.library.path=. -jar enchcracker.jar

**Comment by goncaloRM** [comment]
Nevermind, I pasted all of that into Terminal, but I got an error message saying "enchcracker.cpp:5:10: fatal error: 'jni.h' file not found"

**Comment by goncaloRM** [comment]
After looking thorugh another issue thread that was recently closed, I have successfully gotten to this part:

Type in:

export JAVA_HOME="the_path_you_found_above"
Then hit <control>x to exit and then y to save the changes

But when I try to execute the next step:

Finally

source ~/.bash_profile

It gives me an error. What do I do?

**Comment by Earthcomputer** [comment]
I don't know sorry, I don't own a mac

**Comment by Earthcomputer** [comment]
Should be fixed now with the removal of the native library
