### ISSUE TITLE
jarfile

### ISSUE THREAD

**Issue by iagamer** [Earthcomputer/EnchantmentCracker#66]
it says unable to access jarfile... What should I do now

**Comment by iagamer** [comment]
I'm windows

**Comment by iagamer** [comment]
Please answer

**Comment by Earthcomputer** [comment]
Make sure you extracted it to somewhere Windows has permission to access the jarfile, like your Desktop. Reply if that doesn't work and I can reopen.

**Comment by iagamer** [comment]
I unzipped everything onto the desktop, but as soon as I opened it, I backed out
