### ISSUE TITLE
Cannot execute the command for the .sh file on Mac

### ISSUE THREAD

**Issue by yes1212** [Earthcomputer/EnchantmentCracker#67]
Cracker won't work, my issue has been described by multiple Mac users in previous issues. But I cannot seem to run the .sh file you put in the read me

Thanks

**Comment by Earthcomputer** [comment]
The "help wanted" label means I don't know the solution and want help from anyone who does know the solution. If you know the solution, please comment on #64. Otherwise, please don't duplicate the issue report.
