### ISSUE TITLE
1.14.2 realm server "player seed not found"

### ISSUE THREAD

**Issue by TheWithz** [Earthcomputer/EnchantmentCracker#69]
Using enchantment cracker v. 1.3, I am unable to calculate the player seed. I've tested multiple setups on the realm server (it's completely vanilla). I will try with the fabric mod next and report back
edit: forgot to mention it's windows
edit 2: java edition, not windows 10

**Comment by Earthcomputer** [comment]
Sorry for the late reply.
Unfortunately the tool doesn't have the necessary information to give a more useful error message than "Player seed not found". What you're doing incorrectly may be one of a number of things:
- Inputting numbers incorrectly (unlikely except for miscounting the bookshelves)
- Following instructions incorrectly (e.g. not doing dummy enchantments at the appropriate times)
- Doing one of the prohibited actions during cracking. Being in beacon range tends to catch a lot of people out.
- Playing on a modded server

If you're absolutely sure it's none of these please reply and I can investigate further.

**Comment by TheWithz** [comment]
It appears I was doing a prohibited action. I can't recall exactly, but I'm
almost certain I was in beacon range. I'll try again with that disabled.
