### ISSUE TITLE
Minecraft 1.14.3 changes to enchantments

### ISSUE THREAD

**Issue by LexiTehGallade** [Earthcomputer/EnchantmentCracker#71]
"Reverted the enchanting system to how it was before 1.14"
Not an issue per se but this tool needs to be updated for 1.14.3 again, as the new crossbow coupled with the older enchantment mechanics of before 1.14 requires a new update to be pushed.

I know you probably know but... yeah a new update was pushed and stuff, and i'm no good with java so... Yeah.

**Comment by Earthcomputer** [comment]
I'm aware. A 1.14.3 version will be released soon.

**Comment by Earthcomputer** [comment]
Reopening until it's released

**Comment by flo9t** [comment]
@Earthcomputer could I get your discord if you dont mind I have a couple of questions. Thanks in advance!
