### ISSUE TITLE
NativeException error

### ISSUE THREAD

**Issue by caer2016** [Earthcomputer/EnchantmentCracker#74]
1. I tried running from the .bat and it only flashes the text "Access is denied" before closing itself
2. I then tried opening the .jar directly, and got the error
![image](https://user-images.githubusercontent.com/52491575/60583778-d766f100-9db5-11e9-9ce7-85dc675e34bc.png)

Clicking the link shown doesn't seem to work, and in the log the error message is "access is denied"
Full log: 
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3354493/enchcracker.log)

**Comment by caer2016** [comment]
Update: i got it to work by running in an administrator account (enabled with the command: "net administrator /active:yes" in cmd with admin privileges)

**Comment by Earthcomputer** [comment]
Make sure you extracted the enchantment cracker to a folder with proper permissions, such as a folder in your desktop for example.
