### ISSUE TITLE
1.14.2 enchanting?

### ISSUE THREAD

**Issue by SatoshiKunXD** [Earthcomputer/EnchantmentCracker#75]
Idk if I'm being stupid or not but ever since I upgraded to 1.14.2 I can't get the cracker to work anymore. I've succeeded one time and that's it. The rest were all failures plus in the manipulations tab I found that you can only predict up to two enchants (which I still can't get). Any reasoning behind this? just curious

**Comment by Earthcomputer** [comment]
This was due to a nerf to enchanting in 1.14 which was reverted in 1.14.3. A 1.14.3 version of the cracker will be released soon.
