### ISSUE TITLE
Enchant Cracker crash if...

### ISSUE THREAD

**Issue by NintendoBest** [Earthcomputer/EnchantmentCracker#8]
See video: 

https://youtu.be/siBLyX6OFtw
Bug 1... finished to get my first Exp seen... entered the numbers and went back to the Exp seend.. it crashed
Bug 2... Just try to add any enchant like (sharpness, respiration, fortune ect) with no level next to it, it will just make crash the Cracker.

Trying to put an unwanted enchant without any level should work (it would tell the cracker to not have any level of this enchant on the item we try to get)
(Affected version 1.1.1)
_____________________________________________________________________________________
Also a quick Suggestion non-related to the issue:
When we are adding the numbers on the Xp seed slots.
When we press "Add info" I feel it should get ride of all number put in Slot 1 2 3 and put the previous added number next to the case

And it would go like this:

Bookshelf around table: [15]
Slot1 [5    ]
Slot2 [8    ]
Slot3 [30  ]
-> Add info ->
Bookshelf around table: [*empty*] 15
Slot1 [*empty*] 5
Slot2 [*empty*] 8
Slot3 [*empty*] 30
Side note: Some peoples, might dislike this, so an option could be add to able/disable this...

**Comment by NintendoBest** [comment]
*Bug 1 is hard to reproduce. You might have to try few time before it happen.

**Comment by Earthcomputer** [comment]
Hi,

Since version 1.1, I've added log files to help me debug this kind of thing. They are in `enchcracker.log` and are reset every time you restart the program. Please include the contents of this file in bug reports from now on.

**Comment by Earthcomputer** [comment]
Also, please try to split unrelated issues into separate bug reports in future. I've fixed the first one, so I'm closing this and creating two new bug reports for the other two. Have a nice day!
