### ISSUE TITLE
Out of Memory Issues

### ISSUE THREAD

**Issue by TG310** [Earthcomputer/EnchantmentCracker#80]
My computer don't have enough Ram to storge all search result. Can you make it store result on computer storge and not on ram

**Comment by MCRcortex** [comment]
have a look at enabling or increasing you swap file storage

**Comment by Hexicube** [comment]
This should be improved for the next release once my PR is checked, when testing I found it would only go to about 600MB.

**Comment by Earthcomputer** [comment]
Just waiting on the next release to be ready :)

**Comment by Earthcomputer** [comment]
And now the release is out
