### ISSUE TITLE
No possible seeds, im minecraft 1.14.3

### ISSUE THREAD

**Issue by DonJTru** [Earthcomputer/EnchantmentCracker#81]

**Comment by Earthcomputer** [comment]
Minecraft 1.14.3 isn't supported yet, but it shouldn't break in this way. First off, please provide the `enchcracker.log` file so I can take a look at it, and in the mean time double check you aren't on a Spigot server and are doing everything correctly.

**Comment by Dysproh** [comment]
I'm getting the same problem on a paper server. Heres my log:
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3370036/enchcracker.log)

**Comment by oiajweoijaweoij** [comment]
Same here. Paper server. 1.14.3

[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3372809/enchcracker.log)

Thanks!

**Comment by oiajweoijaweoij** [comment]
I know this isn't exactly the proper place for this question but how can I compile and test the Github merge requests in advance?  Is it way more involved than installing the Windows Java JDK vs JRE?  I thought I was close earlier but then things fell apart. Please advise if you can and sorry for bringing this up here.

**Comment by Earthcomputer** [comment]
> Paper server. 1.14.3

Please, you two, do read my comment from before :) it doesn't work on paper or 1.14.3.

> how can I compile and test the Github merge requests in advance

You pull from that branch and compile. For compiling you can either use an IDE or javac, Google is your friend.

**Comment by DonJTru** [comment]
I dont believe that I'm a paper server I'll check and let you know

**Comment by DonJTru** [comment]
Sorry I'm sending this via email, my github account isnt working atm.
