### ISSUE TITLE
No possible seeds, using MC 1.14.2

### ISSUE THREAD

**Issue by smellysmellwhichsmells** [Earthcomputer/EnchantmentCracker#82]
Can't get any seeds, here my log.
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3375913/enchcracker.log)

**Comment by Earthcomputer** [comment]
Are you on a Spigot or paper server?

**Comment by LANKDORD** [comment]
Is EnchantmentCracker incompatible with Spigot servers? I just tried it on a Spigot server and no player seed was found.
