### ISSUE TITLE
Player seed not found in 1.13.2

### ISSUE THREAD

**Issue by ianpoe** [Earthcomputer/EnchantmentCracker#86]
I know there are already a couple issues for this, but all of them have been responded with "you didn't do it right." I know for sure I entered every number correctly, and followed all of the instructions. There should be no way for the xp seeds not to be correct.

**Comment by Earthcomputer** [comment]
It has been tested numerous times on 1.13.2 and it works, so it must be you doing something incorrectly. Unfortunately the tool doesn't have the necessary information to give a more useful error message than "Player seed not found". What you're doing incorrectly may be one of a number of things:
- Inputting numbers incorrectly (unlikely except for miscounting the bookshelves)
- Following instructions incorrectly (e.g. not doing dummy enchantments at the appropriate times)
- Doing one of the prohibited actions during cracking. Being in beacon range tends to catch a lot of people out.
- Playing on a modded server
If you're absolutely sure it's none of these please reply and I can investigate further.

**Comment by ianpoe** [comment]
I tried on single and multiplayer, I didn’t move during the processes, so
unless breaking torches causes the rand to advance nothing happened there,
and I tried multiple times, so I’m pretty sure I didn’t input numbers
incorrectly

**Comment by Earthcomputer** [comment]
Thanks for your response! If it isn't too much effort, could you produce a video (or at least a world download) of it failing to work?

**Comment by ianpoe** [comment]
Yeah, I’ll record one later today.

**Comment by Earthcomputer** [comment]
Closing till I get a reply :)
