### ISSUE TITLE
32 Bit Java Issue and OutOfMemory Error

### ISSUE THREAD

**Issue by pumalion** [Earthcomputer/EnchantmentCracker#87]
I updated to Java64 Bit multiple times and even had 64 bit before I updated java I don't understand but it keeps saying that I don't have 64 bit and regardless of that, it says I don't have enough memory when I'm sure I do
![Github1](https://user-images.githubusercontent.com/53406997/62010902-e11a1500-b125-11e9-81b7-a8e9e7857c40.PNG)
![Github2](https://user-images.githubusercontent.com/53406997/62010908-fabb5c80-b125-11e9-8f85-8f762df5335d.PNG)
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3439422/enchcracker.log)

**Comment by MCRcortex** [comment]
according to the enchcracker.log

[2019-07-28 10:53:19] [/INFO]: System details:
[2019-07-28 10:53:19] [/INFO]: OS = Windows 10 10.0
[2019-07-28 10:53:19] [/INFO]: Arch (either OS/Java) = x86
[2019-07-28 10:53:19] [/INFO]: Java = 1.8.0_221
[2019-07-28 10:53:19] [/INFO]: Java arch = 32

your running java 32 bit

**Comment by pumalion** [comment]
> according to the enchcracker.log
> 
> [2019-07-28 10:53:19] [/INFO]: System details:
> [2019-07-28 10:53:19] [/INFO]: OS = Windows 10 10.0
> [2019-07-28 10:53:19] [/INFO]: Arch (either OS/Java) = x86
> [2019-07-28 10:53:19] [/INFO]: Java = 1.8.0_221
> [2019-07-28 10:53:19] [/INFO]: Java arch = 32
> 
> your running java 32 bit

Well how do I switch to 64 Bit because I updated java more than once and it was 64 bit both times

**Comment by Earthcomputer** [comment]
Maybe you haven't properly removed your old Java installation?
