### ISSUE TITLE
Error on startup (This is for the 1.11 - 1.12.2 one)

### ISSUE THREAD

**Issue by Pryerat** [Earthcomputer/EnchantmentCracker#89]
An error pops up while starting. I'm not an expert with java so I'm just including pictures of the error and the logs, the error is a little different every time.
[https://prnt.sc/om9m5z](https://prnt.sc/om9m5z)
[https://prnt.sc/om9n6z](https://prnt.sc/om9n6z)
[https://prnt.sc/om9ne9](https://prnt.sc/om9ne9)
[https://prnt.sc/om9nm0](https://prnt.sc/om9nm0)

Had to rename the log files to upload them on here

[enchcracker(log1).log](https://github.com/Earthcomputer/EnchantmentCracker/files/3449622/enchcracker.log1.log)
[enchcracker(log2).log](https://github.com/Earthcomputer/EnchantmentCracker/files/3449623/enchcracker.log2.log)
[enchcracker(log3).log](https://github.com/Earthcomputer/EnchantmentCracker/files/3449624/enchcracker.log3.log)
[enchcracker(log4).log](https://github.com/Earthcomputer/EnchantmentCracker/files/3449625/enchcracker.log4.log)
[enchcracker(log5).log](https://github.com/Earthcomputer/EnchantmentCracker/files/3449626/enchcracker.log5.log)

**Comment by Earthcomputer** [comment]
Try allocating more memory?
Old versions aren't supported, though, so this issue is invalid.
It's a much-requested feature though, which I'm aware of (#77)
