### ISSUE TITLE
Just a small question

### ISSUE THREAD

**Issue by TG310** [Earthcomputer/EnchantmentCracker#93]
I tried on a faction server but it couldn't calculate the player seed though I already found 2 enchant seeds.
But the server have a plugin that add enchant into the game. Does it effect the process of finding to correct seed.

I also have a suggestion:Can you add a "All other enchant" button to the enchant tab cause when you enchant a book its very time comsuming to add all the dont wanted enchant when you only need 1 or 2 enchant.
And please update 1.11-1.12 if you have changes.

**Comment by Earthcomputer** [comment]
If the server has plugins it might break enchantment cracking, and there's not much I can do about that.
As for the second question, I can't see it often mattering if enchanted books have other enchantments.
The next update will have a drop-down menu allowing you to select previous Minecraft versions.
