### ISSUE TITLE
Out of Memory Issue in version 1.4

### ISSUE THREAD

**Issue by rombachar** [Earthcomputer/EnchantmentCracker#94]
![Capture](https://user-images.githubusercontent.com/20204078/62453261-a72abd80-b77a-11e9-927d-e34b6a4b9c87.PNG)

**Comment by hube12** [comment]
did you launch with the given .bat or .sh?

**Comment by rombachar** [comment]
Yes. I used the .bat file. This error comes up when I try to search the XP seed

**Comment by Earthcomputer** [comment]
Can you please give `enchcracker.log` as the popup tells you to?

**Comment by rombachar** [comment]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3466871/enchcracker.log)

**Comment by hube12** [comment]
how much ram does your system has?

**Comment by rombachar** [comment]
16GB

**Comment by Earthcomputer** [comment]
How many available processors? (dual core, quad core, etc)

**Comment by rombachar** [comment]
Octo core

**Comment by Earthcomputer** [comment]
Okay so in theory it's crashed while trying to allocate (8-1) * 10000000 * 4 bytes = 280MB. That isn't a lot. Do you have a lot of other programs running which might be taking up all your RAM?

**Comment by rombachar** [comment]
I just tested and after the pop up appears the program seems to continue searching for the seed in the background. While it was doing that I checked task manager and the program takes up about 250 MB of RAM and around 65% of my CPU. Before I ran the program all the other programs that are currently running on my computer (Minecraft, Chrome, Diiscord and Windows) are taking about 44% of my RAM capacity.

**Comment by Earthcomputer** [comment]
Try opening the command prompt in the enchcracker directory, and running it with the following 2 commands at let me know if it works:
```
set JAVA_OPTS=-Xss512M
enchcracker.bat
```

**Comment by rombachar** [comment]
![image](https://user-images.githubusercontent.com/20204078/62456347-e1975900-b780-11e9-9fda-1f5267f755bd.png)
I dont know if I did it right but that what it gave me

**Comment by Earthcomputer** [comment]
Sorry the first command was wrong, it should have been
```
set JAVA_OPTS=-Xms1G
```
(Xms rather than Xss, also increased 512M to 1G in hindsight. Increase this more if it still doesn't work)

**Comment by rombachar** [comment]
Seems to work now. Do I have to open the enchcracker.bat this way everytime now?

**Comment by MCRcortex** [comment]
no
you can edit the enchcracker.bat and put that line at the top of the file

**Comment by Earthcomputer** [comment]
For the moment. I'll see if I can make it the default in future versions.

**Comment by rombachar** [comment]
Will do. Thank you very much 😄

**Comment by rombachar** [comment]
After finding the first XP seed I tried searching for the second one and when it got to 100% I got the same error. I tried restarting the program and Inserting the first seed manually and only tried to find the second seed but the same happened.

**Comment by rombachar** [comment]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3467159/enchcracker.log)

**Comment by Earthcomputer** [comment]
This time there are 75M possible seeds, which is a bit more than last time. Try increasing memory again to 2G?

**Comment by rombachar** [comment]
The program won't launch if I try 2G even if I run it as admin
