### ISSUE TITLE
1.4.1 won't start

### ISSUE THREAD

**Issue by Schnitzelman21** [Earthcomputer/EnchantmentCracker#95]
As mentioned version 1.4.1 gives me an error on startup and no gui pops up. 
Version 1.4 starts fine however so it's not that big of a deal.

[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3467393/enchcracker.log)

**Comment by Earthcomputer** [comment]
Confirmed, that's weird, it starts in the IDE

**Comment by Earthcomputer** [comment]
And this is the culprit https://stackoverflow.com/questions/26463083/gradle-1-12-corrupts-image-files

**Comment by Earthcomputer** [comment]
Fixed in 1.4.2
