### ISSUE TITLE
[Enhancement] Make tab jump order more intuitive

### ISSUE THREAD

**Issue by datatags** [Earthcomputer/EnchantmentCracker#96]
Currently, jumping between text boxes by pressing tab goes top to bottom.
![current](https://user-images.githubusercontent.com/17661376/62482705-c1f53600-b76a-11e9-96eb-140de5f395ef.PNG)
It would be more helpful if each cracker section went top to bottom, like
![revised](https://user-images.githubusercontent.com/17661376/62482732-d6d1c980-b76a-11e9-8093-5bcd06f28b40.PNG)

I did a bit of googling and it looks like one way might be using the [FocusTraversalPolicy](https://docs.oracle.com/javase/8/docs/api/java/awt/FocusTraversalPolicy.html).  I don't know anything about swing so I'm going to have to leave this up to you.

**Comment by Earthcomputer** [comment]
Implemented, it will be in the next update. If you want to try it before then, feel free to build from source.
