### ISSUE TITLE
Can no longer force custom Enchantment seed or easily copy the provided one

### ISSUE THREAD

**Issue by PKMWM1** [Earthcomputer/EnchantmentCracker#97]
There was an option in previous versions which allowed you to inject your full player enchantment seed if you had some other way of acquiring it. Which I do by using cheat engine. However, in the latest version, that option no longer seems to exist, so I need to inject the two lesser enchantment seeds to set the program to the main seed even though I have it already. I also cannot simply copy the seed out of the program to inject it into cheat engine and have to type it by hand. Not a major issue, but it is still a quality of life feature that was in previous versions. Another one that is removed is not being able to see which bookshelf and level combinations I have already inserted into the program.

**Comment by Earthcomputer** [comment]
#242
