### ISSUE TITLE
Imgur link in Readme is broken.

### ISSUE THREAD

**Issue by Immrspy** [Earthcomputer/EnchantmentCracker#98]
The Imgur link found in the Readme file for "how to use" no longer works (https://imgur.com/a/oaxCC5x). I've converted the README.md to a txt file to upload here.
[README.txt](https://github.com/Earthcomputer/EnchantmentCracker/files/3478451/README.txt)

**Comment by Earthcomputer** [comment]
The link is working for me...

**Comment by Immrspy** [comment]
I'm dumb. I coppied the close parenthesis into the URL... lol.
